// This file is auto-generated by @hey-api/openapi-ts

export type AccountGroup = {
    readonly id?: number;
    name?: string;
    readonly 'x-class-name'?: string;
};

export type Account = {
    id?: number;
    logoId?: number;
    name?: string;
    readonly 'x-class-name'?: string;
};

export type Channel = {
    currencyCode?: string;
    externalReferenceCode?: string;
    id?: number;
    name?: string;
    siteGroupId?: number;
    type?: string;
    readonly 'x-class-name'?: string;
};

export type OrderType = {
    readonly id?: number;
    name?: {
        [key: string]: string;
    };
    readonly 'x-class-name'?: string;
};

export type ReplenishmentItem = {
    availabilityDate?: string;
    externalReferenceCode?: string;
    id?: number;
    quantity?: number;
    sku?: string;
    unitOfMeasureKey?: string;
    warehouseId?: number;
    readonly 'x-class-name'?: string;
};

export type Facet = {
    facetCriteria?: string;
    facetValues?: Array<FacetValue>;
};

export type FacetValue = {
    numberOfOccurrences?: number;
    term?: string;
};

export type PageReplenishmentItem = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<ReplenishmentItem>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PageWarehouseAccountGroup = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<WarehouseAccountGroup>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type WarehouseAccountGroup = {
    accountGroup?: AccountGroup;
    accountGroupExternalReferenceCode?: string;
    accountGroupId: number;
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    readonly warehouseAccountGroupId?: number;
    warehouseExternalReferenceCode?: string;
    warehouseId: number;
    readonly 'x-class-name'?: string;
};

export type PageWarehouseAccount = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<WarehouseAccount>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type WarehouseAccount = {
    account?: Account;
    accountExternalReferenceCode?: string;
    accountId: number;
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    readonly warehouseAccountId?: number;
    warehouseExternalReferenceCode?: string;
    warehouseId: number;
    readonly 'x-class-name'?: string;
};

export type PageWarehouseChannel = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<WarehouseChannel>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type WarehouseChannel = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    channel?: Channel;
    channelExternalReferenceCode?: string;
    channelId: number;
    readonly warehouseChannelId?: number;
    warehouseExternalReferenceCode?: string;
    warehouseId: number;
    readonly 'x-class-name'?: string;
};

export type PageWarehouseItem = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<WarehouseItem>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type WarehouseItem = {
    externalReferenceCode?: string;
    id?: number;
    modifiedDate?: string;
    quantity?: number;
    reservedQuantity?: number;
    sku?: string;
    unitOfMeasureKey?: string;
    warehouseExternalReferenceCode?: string;
    warehouseId?: number;
    readonly 'x-class-name'?: string;
};

export type PageWarehouseOrderType = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<WarehouseOrderType>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type WarehouseOrderType = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    orderType?: OrderType;
    orderTypeExternalReferenceCode?: string;
    orderTypeId: number;
    priority?: number;
    warehouseExternalReferenceCode?: string;
    warehouseId: number;
    readonly warehouseOrderTypeId?: number;
    readonly 'x-class-name'?: string;
};

export type Warehouse = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    active?: boolean;
    city?: string;
    countryISOCode?: string;
    description?: {
        [key: string]: string;
    };
    externalReferenceCode?: string;
    id?: number;
    latitude?: number;
    longitude?: number;
    name?: {
        [key: string]: string;
    };
    regionISOCode?: string;
    street1?: string;
    street2?: string;
    street3?: string;
    type?: string;
    warehouseItems?: Array<WarehouseItem>;
    zip?: string;
    readonly 'x-class-name'?: string;
};

export type PageWarehouse = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<Warehouse>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type GetWarehouseAccountGroupAccountGroupData = {
    body?: never;
    path: {
        warehouseAccountGroupId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-account-groups/{warehouseAccountGroupId}/account-group';
};

export type GetWarehouseAccountGroupAccountGroupResponses = {
    /**
     * default response
     */
    default: AccountGroup;
};

export type GetWarehouseAccountGroupAccountGroupResponse = GetWarehouseAccountGroupAccountGroupResponses[keyof GetWarehouseAccountGroupAccountGroupResponses];

export type GetWarehouseAccountAccountData = {
    body?: never;
    path: {
        warehouseAccountId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-accounts/{warehouseAccountId}/account';
};

export type GetWarehouseAccountAccountResponses = {
    /**
     * default response
     */
    default: Account;
};

export type GetWarehouseAccountAccountResponse = GetWarehouseAccountAccountResponses[keyof GetWarehouseAccountAccountResponses];

export type GetWarehouseChannelChannelData = {
    body?: never;
    path: {
        warehouseChannelId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-channels/{warehouseChannelId}/channel';
};

export type GetWarehouseChannelChannelResponses = {
    /**
     * default response
     */
    default: Channel;
};

export type GetWarehouseChannelChannelResponse = GetWarehouseChannelChannelResponses[keyof GetWarehouseChannelChannelResponses];

export type GetWarehouseOrderTypeOrderTypeData = {
    body?: never;
    path: {
        warehouseOrderTypeId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-order-types/{warehouseOrderTypeId}/order-type';
};

export type GetWarehouseOrderTypeOrderTypeResponses = {
    /**
     * default response
     */
    default: OrderType;
};

export type GetWarehouseOrderTypeOrderTypeResponse = GetWarehouseOrderTypeOrderTypeResponses[keyof GetWarehouseOrderTypeOrderTypeResponses];

export type DeleteReplenishmentItemData = {
    body?: never;
    path: {
        replenishmentItemId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/replenishment-items/{replenishmentItemId}';
};

export type DeleteReplenishmentItemResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetReplenishmentItemData = {
    body?: never;
    path: {
        replenishmentItemId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/replenishment-items/{replenishmentItemId}';
};

export type GetReplenishmentItemResponses = {
    /**
     * default response
     */
    default: ReplenishmentItem;
};

export type GetReplenishmentItemResponse = GetReplenishmentItemResponses[keyof GetReplenishmentItemResponses];

export type PatchReplenishmentItemData = {
    body?: ReplenishmentItem;
    path: {
        replenishmentItemId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/replenishment-items/{replenishmentItemId}';
};

export type PatchReplenishmentItemResponses = {
    /**
     * default response
     */
    default: ReplenishmentItem;
};

export type PatchReplenishmentItemResponse = PatchReplenishmentItemResponses[keyof PatchReplenishmentItemResponses];

export type DeleteReplenishmentItemBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/replenishment-items/batch';
};

export type DeleteReplenishmentItemBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteReplenishmentItemByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/replenishment-items/by-externalReferenceCode/{externalReferenceCode}';
};

export type DeleteReplenishmentItemByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetReplenishmentItemByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/replenishment-items/by-externalReferenceCode/{externalReferenceCode}';
};

export type GetReplenishmentItemByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: ReplenishmentItem;
};

export type GetReplenishmentItemByExternalReferenceCodeResponse = GetReplenishmentItemByExternalReferenceCodeResponses[keyof GetReplenishmentItemByExternalReferenceCodeResponses];

export type PatchReplenishmentItemByExternalReferenceCodeData = {
    body?: ReplenishmentItem;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/replenishment-items/by-externalReferenceCode/{externalReferenceCode}';
};

export type PatchReplenishmentItemByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: ReplenishmentItem;
};

export type PatchReplenishmentItemByExternalReferenceCodeResponse = PatchReplenishmentItemByExternalReferenceCodeResponses[keyof PatchReplenishmentItemByExternalReferenceCodeResponses];

export type PutReplenishmentItemByExternalReferenceCodeData = {
    body?: ReplenishmentItem;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/replenishment-items/by-externalReferenceCode/{externalReferenceCode}';
};

export type PutReplenishmentItemByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: ReplenishmentItem;
};

export type PutReplenishmentItemByExternalReferenceCodeResponse = PutReplenishmentItemByExternalReferenceCodeResponses[keyof PutReplenishmentItemByExternalReferenceCodeResponses];

export type GetReplenishmentItemsPageData = {
    body?: never;
    path: {
        sku: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/skus/by-sku/{sku}/replenishment-items';
};

export type GetReplenishmentItemsPageResponses = {
    /**
     * default response
     */
    default: PageReplenishmentItem;
};

export type GetReplenishmentItemsPageResponse = GetReplenishmentItemsPageResponses[keyof GetReplenishmentItemsPageResponses];

export type GetWarehouseIdReplenishmentItemsPageData = {
    body?: never;
    path: {
        warehouseId: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{warehouseId}/replenishment-items';
};

export type GetWarehouseIdReplenishmentItemsPageResponses = {
    /**
     * default response
     */
    default: PageReplenishmentItem;
};

export type GetWarehouseIdReplenishmentItemsPageResponse = GetWarehouseIdReplenishmentItemsPageResponses[keyof GetWarehouseIdReplenishmentItemsPageResponses];

export type PostReplenishmentItemData = {
    body?: ReplenishmentItem;
    path: {
        warehouseId: string;
        sku: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{warehouseId}/skus/by-sku/{sku}/replenishment-items';
};

export type PostReplenishmentItemResponses = {
    /**
     * default response
     */
    default: ReplenishmentItem;
};

export type PostReplenishmentItemResponse = PostReplenishmentItemResponses[keyof PostReplenishmentItemResponses];

export type PostReplenishmentItemBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path: {
        warehouseId: string;
        sku: string;
    };
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{warehouseId}/skus/by-sku/{sku}/replenishment-items/batch';
};

export type PostReplenishmentItemBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostReplenishmentItemsPageExportBatchData = {
    body?: never;
    path: {
        sku: string;
    };
    query?: {
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/skus/by-sku/{sku}/replenishment-items/export-batch';
};

export type PostReplenishmentItemsPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseAccountGroupData = {
    body?: never;
    path: {
        warehouseAccountGroupId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-account-groups/{warehouseAccountGroupId}';
};

export type DeleteWarehouseAccountGroupResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseAccountGroupBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-account-groups/batch';
};

export type DeleteWarehouseAccountGroupBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetWarehouseByExternalReferenceCodeWarehouseAccountGroupsPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}/warehouse-account-groups';
};

export type GetWarehouseByExternalReferenceCodeWarehouseAccountGroupsPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseAccountGroup;
};

export type GetWarehouseByExternalReferenceCodeWarehouseAccountGroupsPageResponse = GetWarehouseByExternalReferenceCodeWarehouseAccountGroupsPageResponses[keyof GetWarehouseByExternalReferenceCodeWarehouseAccountGroupsPageResponses];

export type PostWarehouseByExternalReferenceCodeWarehouseAccountGroupData = {
    body?: WarehouseAccountGroup;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}/warehouse-account-groups';
};

export type PostWarehouseByExternalReferenceCodeWarehouseAccountGroupResponses = {
    /**
     * default response
     */
    default: WarehouseAccountGroup;
};

export type PostWarehouseByExternalReferenceCodeWarehouseAccountGroupResponse = PostWarehouseByExternalReferenceCodeWarehouseAccountGroupResponses[keyof PostWarehouseByExternalReferenceCodeWarehouseAccountGroupResponses];

export type GetWarehouseIdWarehouseAccountGroupsPageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}/warehouse-account-groups';
};

export type GetWarehouseIdWarehouseAccountGroupsPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseAccountGroup;
};

export type GetWarehouseIdWarehouseAccountGroupsPageResponse = GetWarehouseIdWarehouseAccountGroupsPageResponses[keyof GetWarehouseIdWarehouseAccountGroupsPageResponses];

export type PostWarehouseIdWarehouseAccountGroupData = {
    body?: WarehouseAccountGroup;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}/warehouse-account-groups';
};

export type PostWarehouseIdWarehouseAccountGroupResponses = {
    /**
     * default response
     */
    default: WarehouseAccountGroup;
};

export type PostWarehouseIdWarehouseAccountGroupResponse = PostWarehouseIdWarehouseAccountGroupResponses[keyof PostWarehouseIdWarehouseAccountGroupResponses];

export type PostWarehouseIdWarehouseAccountGroupBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/warehouse-account-groups/batch';
};

export type PostWarehouseIdWarehouseAccountGroupBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseAccountData = {
    body?: never;
    path: {
        warehouseAccountId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-accounts/{warehouseAccountId}';
};

export type DeleteWarehouseAccountResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseAccountBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-accounts/batch';
};

export type DeleteWarehouseAccountBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetWarehouseByExternalReferenceCodeWarehouseAccountsPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}/warehouse-accounts';
};

export type GetWarehouseByExternalReferenceCodeWarehouseAccountsPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseAccount;
};

export type GetWarehouseByExternalReferenceCodeWarehouseAccountsPageResponse = GetWarehouseByExternalReferenceCodeWarehouseAccountsPageResponses[keyof GetWarehouseByExternalReferenceCodeWarehouseAccountsPageResponses];

export type PostWarehouseByExternalReferenceCodeWarehouseAccountData = {
    body?: WarehouseAccount;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}/warehouse-accounts';
};

export type PostWarehouseByExternalReferenceCodeWarehouseAccountResponses = {
    /**
     * default response
     */
    default: WarehouseAccount;
};

export type PostWarehouseByExternalReferenceCodeWarehouseAccountResponse = PostWarehouseByExternalReferenceCodeWarehouseAccountResponses[keyof PostWarehouseByExternalReferenceCodeWarehouseAccountResponses];

export type GetWarehouseIdWarehouseAccountsPageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}/warehouse-accounts';
};

export type GetWarehouseIdWarehouseAccountsPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseAccount;
};

export type GetWarehouseIdWarehouseAccountsPageResponse = GetWarehouseIdWarehouseAccountsPageResponses[keyof GetWarehouseIdWarehouseAccountsPageResponses];

export type PostWarehouseIdWarehouseAccountData = {
    body?: WarehouseAccount;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}/warehouse-accounts';
};

export type PostWarehouseIdWarehouseAccountResponses = {
    /**
     * default response
     */
    default: WarehouseAccount;
};

export type PostWarehouseIdWarehouseAccountResponse = PostWarehouseIdWarehouseAccountResponses[keyof PostWarehouseIdWarehouseAccountResponses];

export type PostWarehouseIdWarehouseAccountBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/warehouse-accounts/batch';
};

export type PostWarehouseIdWarehouseAccountBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseChannelData = {
    body?: never;
    path: {
        warehouseChannelId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-channels/{warehouseChannelId}';
};

export type DeleteWarehouseChannelResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseChannelBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-channels/batch';
};

export type DeleteWarehouseChannelBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetWarehouseByExternalReferenceCodeWarehouseChannelsPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}/warehouse-channels';
};

export type GetWarehouseByExternalReferenceCodeWarehouseChannelsPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseChannel;
};

export type GetWarehouseByExternalReferenceCodeWarehouseChannelsPageResponse = GetWarehouseByExternalReferenceCodeWarehouseChannelsPageResponses[keyof GetWarehouseByExternalReferenceCodeWarehouseChannelsPageResponses];

export type PostWarehouseByExternalReferenceCodeWarehouseChannelData = {
    body?: WarehouseChannel;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}/warehouse-channels';
};

export type PostWarehouseByExternalReferenceCodeWarehouseChannelResponses = {
    /**
     * default response
     */
    default: WarehouseChannel;
};

export type PostWarehouseByExternalReferenceCodeWarehouseChannelResponse = PostWarehouseByExternalReferenceCodeWarehouseChannelResponses[keyof PostWarehouseByExternalReferenceCodeWarehouseChannelResponses];

export type GetWarehouseIdWarehouseChannelsPageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}/warehouse-channels';
};

export type GetWarehouseIdWarehouseChannelsPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseChannel;
};

export type GetWarehouseIdWarehouseChannelsPageResponse = GetWarehouseIdWarehouseChannelsPageResponses[keyof GetWarehouseIdWarehouseChannelsPageResponses];

export type PostWarehouseIdWarehouseChannelData = {
    body?: WarehouseChannel;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}/warehouse-channels';
};

export type PostWarehouseIdWarehouseChannelResponses = {
    /**
     * default response
     */
    default: WarehouseChannel;
};

export type PostWarehouseIdWarehouseChannelResponse = PostWarehouseIdWarehouseChannelResponses[keyof PostWarehouseIdWarehouseChannelResponses];

export type PostWarehouseIdWarehouseChannelBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/warehouse-channels/batch';
};

export type PostWarehouseIdWarehouseChannelBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseItemData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouseItems/{id}';
};

export type DeleteWarehouseItemResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetWarehouseItemData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouseItems/{id}';
};

export type GetWarehouseItemResponses = {
    /**
     * default response
     */
    default: WarehouseItem;
};

export type GetWarehouseItemResponse = GetWarehouseItemResponses[keyof GetWarehouseItemResponses];

export type PatchWarehouseItemData = {
    body?: WarehouseItem;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouseItems/{id}';
};

export type PatchWarehouseItemResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseItemBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouseItems/batch';
};

export type DeleteWarehouseItemBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseItemByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouseItems/by-externalReferenceCode/{externalReferenceCode}';
};

export type DeleteWarehouseItemByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetWarehouseItemByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouseItems/by-externalReferenceCode/{externalReferenceCode}';
};

export type GetWarehouseItemByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: WarehouseItem;
};

export type GetWarehouseItemByExternalReferenceCodeResponse = GetWarehouseItemByExternalReferenceCodeResponses[keyof GetWarehouseItemByExternalReferenceCodeResponses];

export type PatchWarehouseItemByExternalReferenceCodeData = {
    body?: WarehouseItem;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouseItems/by-externalReferenceCode/{externalReferenceCode}';
};

export type PatchWarehouseItemByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostWarehouseItemByExternalReferenceCodeData = {
    body?: WarehouseItem;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouseItems/by-externalReferenceCode/{externalReferenceCode}';
};

export type PostWarehouseItemByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: WarehouseItem;
};

export type PostWarehouseItemByExternalReferenceCodeResponse = PostWarehouseItemByExternalReferenceCodeResponses[keyof PostWarehouseItemByExternalReferenceCodeResponses];

export type PutWarehouseItemByExternalReferenceCodeData = {
    body?: WarehouseItem;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouseItems/by-externalReferenceCode/{externalReferenceCode}';
};

export type PutWarehouseItemByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: WarehouseItem;
};

export type PutWarehouseItemByExternalReferenceCodeResponse = PutWarehouseItemByExternalReferenceCodeResponses[keyof PutWarehouseItemByExternalReferenceCodeResponses];

export type GetWarehouseByExternalReferenceCodeWarehouseItemsPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}/warehouseItems';
};

export type GetWarehouseByExternalReferenceCodeWarehouseItemsPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseItem;
};

export type GetWarehouseByExternalReferenceCodeWarehouseItemsPageResponse = GetWarehouseByExternalReferenceCodeWarehouseItemsPageResponses[keyof GetWarehouseByExternalReferenceCodeWarehouseItemsPageResponses];

export type PostWarehouseByExternalReferenceCodeWarehouseItemData = {
    body?: WarehouseItem;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}/warehouseItems';
};

export type PostWarehouseByExternalReferenceCodeWarehouseItemResponses = {
    /**
     * default response
     */
    default: WarehouseItem;
};

export type PostWarehouseByExternalReferenceCodeWarehouseItemResponse = PostWarehouseByExternalReferenceCodeWarehouseItemResponses[keyof PostWarehouseByExternalReferenceCodeWarehouseItemResponses];

export type GetWarehouseIdWarehouseItemsPageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}/warehouseItems';
};

export type GetWarehouseIdWarehouseItemsPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseItem;
};

export type GetWarehouseIdWarehouseItemsPageResponse = GetWarehouseIdWarehouseItemsPageResponses[keyof GetWarehouseIdWarehouseItemsPageResponses];

export type PostWarehouseIdWarehouseItemData = {
    body?: WarehouseItem;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}/warehouseItems';
};

export type PostWarehouseIdWarehouseItemResponses = {
    /**
     * default response
     */
    default: WarehouseItem;
};

export type PostWarehouseIdWarehouseItemResponse = PostWarehouseIdWarehouseItemResponses[keyof PostWarehouseIdWarehouseItemResponses];

export type GetWarehouseItemsUpdatedPageData = {
    body?: never;
    path?: never;
    query?: {
        end?: string;
        page?: string;
        pageSize?: string;
        start?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouseItems/updated';
};

export type GetWarehouseItemsUpdatedPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseItem;
};

export type GetWarehouseItemsUpdatedPageResponse = GetWarehouseItemsUpdatedPageResponses[keyof GetWarehouseItemsUpdatedPageResponses];

export type PostWarehouseIdWarehouseItemBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/warehouseItems/batch';
};

export type PostWarehouseIdWarehouseItemBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseOrderTypeData = {
    body?: never;
    path: {
        warehouseOrderTypeId: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-order-types/{warehouseOrderTypeId}';
};

export type DeleteWarehouseOrderTypeResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseOrderTypeBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouse-order-types/batch';
};

export type DeleteWarehouseOrderTypeBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetWarehouseByExternalReferenceCodeWarehouseOrderTypesPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}/warehouse-order-types';
};

export type GetWarehouseByExternalReferenceCodeWarehouseOrderTypesPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseOrderType;
};

export type GetWarehouseByExternalReferenceCodeWarehouseOrderTypesPageResponse = GetWarehouseByExternalReferenceCodeWarehouseOrderTypesPageResponses[keyof GetWarehouseByExternalReferenceCodeWarehouseOrderTypesPageResponses];

export type PostWarehouseByExternalReferenceCodeWarehouseOrderTypeData = {
    body?: WarehouseOrderType;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}/warehouse-order-types';
};

export type PostWarehouseByExternalReferenceCodeWarehouseOrderTypeResponses = {
    /**
     * default response
     */
    default: WarehouseOrderType;
};

export type PostWarehouseByExternalReferenceCodeWarehouseOrderTypeResponse = PostWarehouseByExternalReferenceCodeWarehouseOrderTypeResponses[keyof PostWarehouseByExternalReferenceCodeWarehouseOrderTypeResponses];

export type GetWarehouseIdWarehouseOrderTypesPageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}/warehouse-order-types';
};

export type GetWarehouseIdWarehouseOrderTypesPageResponses = {
    /**
     * default response
     */
    default: PageWarehouseOrderType;
};

export type GetWarehouseIdWarehouseOrderTypesPageResponse = GetWarehouseIdWarehouseOrderTypesPageResponses[keyof GetWarehouseIdWarehouseOrderTypesPageResponses];

export type PostWarehouseIdWarehouseOrderTypeData = {
    body?: WarehouseOrderType;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}/warehouse-order-types';
};

export type PostWarehouseIdWarehouseOrderTypeResponses = {
    /**
     * default response
     */
    default: WarehouseOrderType;
};

export type PostWarehouseIdWarehouseOrderTypeResponse = PostWarehouseIdWarehouseOrderTypeResponses[keyof PostWarehouseIdWarehouseOrderTypeResponses];

export type PostWarehouseIdWarehouseOrderTypeBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/warehouse-order-types/batch';
};

export type PostWarehouseIdWarehouseOrderTypeBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteWarehouseByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}';
};

export type DeleteWarehouseByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetWarehouseByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}';
};

export type GetWarehouseByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: Warehouse;
};

export type GetWarehouseByExternalReferenceCodeResponse = GetWarehouseByExternalReferenceCodeResponses[keyof GetWarehouseByExternalReferenceCodeResponses];

export type PatchWarehouseByExternalReferenceCodeData = {
    body?: Warehouse;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}';
};

export type PatchWarehouseByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PutWarehouseByExternalReferenceCodeData = {
    body?: Warehouse;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/by-externalReferenceCode/{externalReferenceCode}';
};

export type PutWarehouseByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: Warehouse;
};

export type PutWarehouseByExternalReferenceCodeResponse = PutWarehouseByExternalReferenceCodeResponses[keyof PutWarehouseByExternalReferenceCodeResponses];

export type DeleteWarehouseIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}';
};

export type DeleteWarehouseIdResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetWarehouseIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}';
};

export type GetWarehouseIdResponses = {
    /**
     * default response
     */
    default: Warehouse;
};

export type GetWarehouseIdResponse = GetWarehouseIdResponses[keyof GetWarehouseIdResponses];

export type PatchWarehouseIdData = {
    body?: Warehouse;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/{id}';
};

export type PatchWarehouseIdResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetWarehousesPageData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses';
};

export type GetWarehousesPageResponses = {
    /**
     * default response
     */
    default: PageWarehouse;
};

export type GetWarehousesPageResponse = GetWarehousesPageResponses[keyof GetWarehousesPageResponses];

export type PostWarehouseData = {
    body?: Warehouse;
    path?: never;
    query?: never;
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses';
};

export type PostWarehouseResponses = {
    /**
     * default response
     */
    default: Warehouse;
};

export type PostWarehouseResponse = PostWarehouseResponses[keyof PostWarehouseResponses];

export type PostWarehouseBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/batch';
};

export type PostWarehouseBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostWarehousesPageExportBatchData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        search?: string;
        sort?: string;
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/headless-commerce-admin-inventory/v1.0/warehouses/export-batch';
};

export type PostWarehousesPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};