// This file is auto-generated by @hey-api/openapi-ts

export type Attachment = {
    readonly externalReferenceCode?: string;
    readonly id?: number;
    readonly title?: string;
    readonly type?: number;
    readonly url?: string;
    readonly 'x-class-name'?: string;
};

export type Facet = {
    facetCriteria?: string;
    facetValues?: Array<FacetValue>;
};

export type FacetValue = {
    numberOfOccurrences?: number;
    term?: string;
};

export type PageAttachment = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<Attachment>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type AttachmentBase64 = {
    /**
     * Base64 encoded file
     */
    attachment?: string;
    externalReferenceCode?: string;
    title?: string;
    readonly 'x-class-name'?: string;
};

export type OrderTransition = {
    comment?: string;
    readonly label?: string;
    name?: string;
    readonly orderId?: number;
    readonly placedOrderId?: number;
    workflowTaskId?: number;
    readonly 'x-class-name'?: string;
};

export type PageOrderTransition = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<OrderTransition>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PlacedOrderAddress = {
    readonly city?: string;
    readonly country?: string;
    readonly countryISOCode?: string;
    readonly description?: string;
    readonly externalReferenceCode?: string;
    readonly id?: number;
    readonly latitude?: number;
    readonly longitude?: number;
    readonly name?: string;
    readonly phoneNumber?: string;
    readonly region?: string;
    readonly regionISOCode?: string;
    readonly street1?: string;
    readonly street2?: string;
    readonly street3?: string;
    readonly subtype?: string;
    readonly type?: string;
    readonly typeId?: number;
    readonly vatNumber?: string;
    readonly zip?: string;
    readonly 'x-class-name'?: string;
};

export type PagePlacedOrderComment = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<PlacedOrderComment>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PlacedOrderComment = {
    readonly author?: string;
    readonly content?: string;
    readonly externalReferenceCode?: string;
    readonly id?: number;
    readonly orderId?: number;
    readonly restricted?: boolean;
    readonly 'x-class-name'?: string;
};

export type PagePlacedOrderItem = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<PlacedOrderItem>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PlacedOrderItem = {
    readonly adaptiveMediaImageHTMLTag?: string;
    readonly customFields?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    /**
     * @deprecated
     */
    readonly deliveryGroup?: string;
    readonly deliveryGroupName?: string;
    readonly errorMessages?: Array<string>;
    readonly externalReferenceCode?: string;
    readonly id?: number;
    readonly name?: string;
    readonly options?: string;
    readonly parentOrderItemId?: number;
    readonly placedOrderItemShipments?: Array<PlacedOrderItemShipment>;
    price?: Price;
    readonly productId?: number;
    readonly productURLs?: {
        [key: string]: string;
    };
    readonly quantity?: number;
    readonly replacedSku?: string;
    readonly requestedDeliveryDate?: string;
    settings?: Settings;
    readonly shippingAddressExternalReferenceCode?: string;
    readonly shippingAddressId?: number;
    readonly sku?: string;
    readonly skuId?: number;
    readonly subscription?: boolean;
    readonly thumbnail?: string;
    readonly unitOfMeasure?: string;
    readonly unitOfMeasureKey?: string;
    readonly valid?: boolean;
    readonly virtualItemURLs?: Array<string>;
    readonly virtualItems?: Array<VirtualItem>;
    readonly 'x-class-name'?: string;
};

export type PlacedOrderItemShipment = {
    readonly accountId?: number;
    readonly author?: string;
    readonly carrier?: string;
    readonly createDate?: string;
    readonly estimatedDeliveryDate?: string;
    readonly estimatedShippingDate?: string;
    readonly externalReferenceCode?: string;
    readonly id?: number;
    readonly modifiedDate?: string;
    readonly orderId?: number;
    readonly quantity?: number;
    readonly shippingAddressId?: number;
    readonly shippingMethodId?: number;
    readonly shippingOptionName?: string;
    status?: Status;
    readonly supplierShipment?: boolean;
    readonly trackingNumber?: string;
    readonly trackingURL?: string;
    readonly unitOfMeasureKey?: string;
    readonly 'x-class-name'?: string;
};

export type Price = {
    readonly currency?: string;
    readonly discount?: number;
    readonly discountFormatted?: string;
    readonly discountPercentage?: string;
    readonly discountPercentageLevel1?: number;
    readonly discountPercentageLevel2?: number;
    readonly discountPercentageLevel3?: number;
    readonly discountPercentageLevel4?: number;
    readonly finalPrice?: number;
    readonly finalPriceFormatted?: string;
    readonly price?: number;
    readonly priceFormatted?: string;
    readonly promoPrice?: number;
    readonly promoPriceFormatted?: string;
    readonly 'x-class-name'?: string;
};

export type Settings = {
    readonly allowedQuantities?: Array<number>;
    readonly maxQuantity?: number;
    readonly minQuantity?: number;
    readonly multipleQuantity?: number;
    readonly 'x-class-name'?: string;
};

export type Status = {
    readonly code?: number;
    readonly label?: string;
    readonly label_i18n?: string;
    readonly 'x-class-name'?: string;
};

export type VirtualItem = {
    readonly url?: string;
    readonly usages?: number;
    readonly version?: string;
    readonly 'x-class-name'?: string;
};

export type PagePlacedOrderItemShipment = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<PlacedOrderItemShipment>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PagePlacedOrder = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<PlacedOrder>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PlacedOrder = {
    readonly account?: string;
    readonly accountId?: number;
    attachments?: Array<Attachment>;
    readonly author?: string;
    readonly channelId?: number;
    readonly couponCode?: string;
    readonly createDate?: string;
    readonly currencyCode?: string;
    customFields?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    readonly errorMessages?: Array<string>;
    readonly externalReferenceCode?: string;
    readonly friendlyURLSeparator?: string;
    readonly id?: number;
    readonly lastPriceUpdateDate?: string;
    readonly modifiedDate?: string;
    name?: string;
    orderStatusInfo?: Status;
    readonly orderType?: string;
    readonly orderTypeExternalReferenceCode?: string;
    readonly orderTypeId?: number;
    readonly orderUUID?: string;
    readonly paymentMethod?: string;
    readonly paymentMethodLabel?: string;
    readonly paymentStatus?: number;
    paymentStatusInfo?: Status;
    readonly paymentStatusLabel?: string;
    placedOrderBillingAddress?: PlacedOrderAddress;
    readonly placedOrderBillingAddressId?: number;
    readonly placedOrderComments?: Array<PlacedOrderComment>;
    readonly placedOrderItems?: Array<PlacedOrderItem>;
    placedOrderShippingAddress?: PlacedOrderAddress;
    readonly placedOrderShippingAddressId?: number;
    printedNote?: string;
    purchaseOrderNumber?: string;
    readonly requestedDeliveryDate?: string;
    shipments?: Shipment;
    readonly shippingMethod?: string;
    readonly shippingOption?: string;
    readonly status?: string;
    steps?: Array<Step>;
    summary?: Summary;
    readonly useAsBilling?: boolean;
    readonly valid?: boolean;
    workflowStatusInfo?: Status;
    readonly 'x-class-name'?: string;
};

export type Shipment = {
    readonly accountId?: number;
    readonly carrier?: string;
    readonly createDate?: string;
    readonly expectedDate?: string;
    readonly externalReferenceCode?: string;
    readonly id?: number;
    readonly itemsCount?: number;
    readonly modifiedDate?: string;
    readonly oneLineAddress?: string;
    readonly orderExternalReferenceCode?: string;
    readonly orderId?: number;
    shippingAddress?: ShippingAddress;
    readonly shippingAddressId?: number;
    readonly shippingDate?: string;
    readonly shippingMethodId?: number;
    readonly shippingOptionName?: string;
    status?: Status;
    readonly trackingNumber?: string;
    readonly trackingURL?: string;
    readonly userName?: string;
    readonly 'x-class-name'?: string;
};

export type ShippingAddress = {
    readonly city?: string;
    readonly countryISOCode?: string;
    readonly description?: string;
    readonly externalReferenceCode?: string;
    readonly id?: number;
    readonly latitude?: number;
    readonly longitude?: number;
    readonly name?: string;
    readonly phoneNumber?: string;
    readonly regionISOCode?: string;
    readonly street1?: string;
    readonly street2?: string;
    readonly street3?: string;
    readonly zip?: string;
    readonly 'x-class-name'?: string;
};

export type Step = {
    readonly id?: string;
    readonly label?: string;
    readonly state?: string;
    readonly 'x-class-name'?: string;
};

export type Summary = {
    readonly currency?: string;
    readonly itemsQuantity?: number;
    readonly shippingDiscountPercentages?: Array<string>;
    readonly shippingDiscountValue?: number;
    readonly shippingDiscountValueFormatted?: string;
    readonly shippingValue?: number;
    readonly shippingValueFormatted?: string;
    readonly shippingValueWithTaxAmount?: number;
    readonly shippingValueWithTaxAmountFormatted?: string;
    readonly subtotal?: number;
    readonly subtotalDiscountPercentages?: Array<string>;
    readonly subtotalDiscountValue?: number;
    readonly subtotalDiscountValueFormatted?: string;
    readonly subtotalFormatted?: string;
    readonly taxValue?: number;
    readonly taxValueFormatted?: string;
    readonly total?: number;
    readonly totalDiscountPercentages?: Array<string>;
    readonly totalDiscountValue?: number;
    readonly totalDiscountValueFormatted?: string;
    readonly totalFormatted?: string;
    readonly 'x-class-name'?: string;
};

export type PageShipment = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<Shipment>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type Term = {
    readonly description?: string;
    externalReferenceCode?: string;
    id?: number;
    readonly name?: string;
    readonly 'x-class-name'?: string;
};

export type DeletePlacedOrderAttachmentData = {
    body?: never;
    path: {
        attachmentId: string;
        placedOrderId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/attachments/{attachmentId}';
};

export type DeletePlacedOrderAttachmentResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeletePlacedOrderByExternalReferenceCodeAttachmentByExternalReferenceCodeAttachmentExternalReferenceCodeData = {
    body?: never;
    path: {
        attachmentExternalReferenceCode: string;
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/attachments/by-externalReferenceCode/{attachmentExternalReferenceCode}';
};

export type DeletePlacedOrderByExternalReferenceCodeAttachmentByExternalReferenceCodeAttachmentExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetPlacedOrderAttachmentsPageData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/attachments';
};

export type GetPlacedOrderAttachmentsPageResponses = {
    /**
     * default response
     */
    default: PageAttachment;
};

export type GetPlacedOrderAttachmentsPageResponse = GetPlacedOrderAttachmentsPageResponses[keyof GetPlacedOrderAttachmentsPageResponses];

export type GetPlacedOrderByExternalReferenceCodeAttachmentsPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/attachments';
};

export type GetPlacedOrderByExternalReferenceCodeAttachmentsPageResponses = {
    /**
     * default response
     */
    default: PageAttachment;
};

export type GetPlacedOrderByExternalReferenceCodeAttachmentsPageResponse = GetPlacedOrderByExternalReferenceCodeAttachmentsPageResponses[keyof GetPlacedOrderByExternalReferenceCodeAttachmentsPageResponses];

export type PostPlacedOrderAttachmentByBase64Data = {
    body?: AttachmentBase64;
    path: {
        placedOrderId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/attachments/by-base64';
};

export type PostPlacedOrderAttachmentByBase64Responses = {
    /**
     * default response
     */
    default: Attachment;
};

export type PostPlacedOrderAttachmentByBase64Response = PostPlacedOrderAttachmentByBase64Responses[keyof PostPlacedOrderAttachmentByBase64Responses];

export type PostPlacedOrderAttachmentsPageExportBatchData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/attachments/export-batch';
};

export type PostPlacedOrderAttachmentsPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostPlacedOrderByExternalReferenceCodeAttachmentByBase64Data = {
    body?: AttachmentBase64;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/attachments/by-base64';
};

export type PostPlacedOrderByExternalReferenceCodeAttachmentByBase64Responses = {
    /**
     * default response
     */
    default: Attachment;
};

export type PostPlacedOrderByExternalReferenceCodeAttachmentByBase64Response = PostPlacedOrderByExternalReferenceCodeAttachmentByBase64Responses[keyof PostPlacedOrderByExternalReferenceCodeAttachmentByBase64Responses];

export type GetPlacedOrderOrderTransitionsPageData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/order-transitions';
};

export type GetPlacedOrderOrderTransitionsPageResponses = {
    /**
     * default response
     */
    default: PageOrderTransition;
};

export type GetPlacedOrderOrderTransitionsPageResponse = GetPlacedOrderOrderTransitionsPageResponses[keyof GetPlacedOrderOrderTransitionsPageResponses];

export type PostPlacedOrderOrderTransitionData = {
    body?: OrderTransition;
    path: {
        placedOrderId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/order-transitions';
};

export type PostPlacedOrderOrderTransitionResponses = {
    /**
     * default response
     */
    default: OrderTransition;
};

export type PostPlacedOrderOrderTransitionResponse = PostPlacedOrderOrderTransitionResponses[keyof PostPlacedOrderOrderTransitionResponses];

export type PostPlacedOrderOrderTransitionBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path: {
        placedOrderId: string;
    };
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/order-transitions/batch';
};

export type PostPlacedOrderOrderTransitionBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostPlacedOrderOrderTransitionsPageExportBatchData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/order-transitions/export-batch';
};

export type PostPlacedOrderOrderTransitionsPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetPlacedOrderByExternalReferenceCodePlacedOrderBillingAddressData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/placed-order-billing-address';
};

export type GetPlacedOrderByExternalReferenceCodePlacedOrderBillingAddressResponses = {
    /**
     * default response
     */
    default: PlacedOrderAddress;
};

export type GetPlacedOrderByExternalReferenceCodePlacedOrderBillingAddressResponse = GetPlacedOrderByExternalReferenceCodePlacedOrderBillingAddressResponses[keyof GetPlacedOrderByExternalReferenceCodePlacedOrderBillingAddressResponses];

export type GetPlacedOrderByExternalReferenceCodePlacedOrderShippingAddressData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/placed-order-shipping-address';
};

export type GetPlacedOrderByExternalReferenceCodePlacedOrderShippingAddressResponses = {
    /**
     * default response
     */
    default: PlacedOrderAddress;
};

export type GetPlacedOrderByExternalReferenceCodePlacedOrderShippingAddressResponse = GetPlacedOrderByExternalReferenceCodePlacedOrderShippingAddressResponses[keyof GetPlacedOrderByExternalReferenceCodePlacedOrderShippingAddressResponses];

export type GetPlacedOrderPlacedOrderBillingAddressData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/placed-order-billing-address';
};

export type GetPlacedOrderPlacedOrderBillingAddressResponses = {
    /**
     * default response
     */
    default: PlacedOrderAddress;
};

export type GetPlacedOrderPlacedOrderBillingAddressResponse = GetPlacedOrderPlacedOrderBillingAddressResponses[keyof GetPlacedOrderPlacedOrderBillingAddressResponses];

export type GetPlacedOrderPlacedOrderShippingAddressData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/placed-order-shipping-address';
};

export type GetPlacedOrderPlacedOrderShippingAddressResponses = {
    /**
     * default response
     */
    default: PlacedOrderAddress;
};

export type GetPlacedOrderPlacedOrderShippingAddressResponse = GetPlacedOrderPlacedOrderShippingAddressResponses[keyof GetPlacedOrderPlacedOrderShippingAddressResponses];

export type GetPlacedOrderByExternalReferenceCodePlacedOrderCommentsPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/placed-order-comments';
};

export type GetPlacedOrderByExternalReferenceCodePlacedOrderCommentsPageResponses = {
    /**
     * default response
     */
    default: PagePlacedOrderComment;
};

export type GetPlacedOrderByExternalReferenceCodePlacedOrderCommentsPageResponse = GetPlacedOrderByExternalReferenceCodePlacedOrderCommentsPageResponses[keyof GetPlacedOrderByExternalReferenceCodePlacedOrderCommentsPageResponses];

export type GetPlacedOrderCommentData = {
    body?: never;
    path: {
        placedOrderCommentId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-order-comments/{placedOrderCommentId}';
};

export type GetPlacedOrderCommentResponses = {
    /**
     * default response
     */
    default: PlacedOrderComment;
};

export type GetPlacedOrderCommentResponse = GetPlacedOrderCommentResponses[keyof GetPlacedOrderCommentResponses];

export type GetPlacedOrderCommentByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-order-comments/by-externalReferenceCode/{externalReferenceCode}';
};

export type GetPlacedOrderCommentByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: PlacedOrderComment;
};

export type GetPlacedOrderCommentByExternalReferenceCodeResponse = GetPlacedOrderCommentByExternalReferenceCodeResponses[keyof GetPlacedOrderCommentByExternalReferenceCodeResponses];

export type GetPlacedOrderPlacedOrderCommentsPageData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/placed-order-comments';
};

export type GetPlacedOrderPlacedOrderCommentsPageResponses = {
    /**
     * default response
     */
    default: PagePlacedOrderComment;
};

export type GetPlacedOrderPlacedOrderCommentsPageResponse = GetPlacedOrderPlacedOrderCommentsPageResponses[keyof GetPlacedOrderPlacedOrderCommentsPageResponses];

export type PostPlacedOrderPlacedOrderCommentsPageExportBatchData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/placed-order-comments/export-batch';
};

export type PostPlacedOrderPlacedOrderCommentsPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetPlacedOrderByExternalReferenceCodePlacedOrderItemsPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        search?: string;
        skuId?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/placed-order-items';
};

export type GetPlacedOrderByExternalReferenceCodePlacedOrderItemsPageResponses = {
    /**
     * default response
     */
    default: PagePlacedOrderItem;
};

export type GetPlacedOrderByExternalReferenceCodePlacedOrderItemsPageResponse = GetPlacedOrderByExternalReferenceCodePlacedOrderItemsPageResponses[keyof GetPlacedOrderByExternalReferenceCodePlacedOrderItemsPageResponses];

export type GetPlacedOrderItemData = {
    body?: never;
    path: {
        placedOrderItemId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-order-items/{placedOrderItemId}';
};

export type GetPlacedOrderItemResponses = {
    /**
     * default response
     */
    default: PlacedOrderItem;
};

export type GetPlacedOrderItemResponse = GetPlacedOrderItemResponses[keyof GetPlacedOrderItemResponses];

export type GetPlacedOrderItemByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-order-items/by-externalReferenceCode/{externalReferenceCode}';
};

export type GetPlacedOrderItemByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: PlacedOrderItem;
};

export type GetPlacedOrderItemByExternalReferenceCodeResponse = GetPlacedOrderItemByExternalReferenceCodeResponses[keyof GetPlacedOrderItemByExternalReferenceCodeResponses];

export type GetPlacedOrderPlacedOrderItemsPageData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
        search?: string;
        skuId?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/placed-order-items';
};

export type GetPlacedOrderPlacedOrderItemsPageResponses = {
    /**
     * default response
     */
    default: PagePlacedOrderItem;
};

export type GetPlacedOrderPlacedOrderItemsPageResponse = GetPlacedOrderPlacedOrderItemsPageResponses[keyof GetPlacedOrderPlacedOrderItemsPageResponses];

export type PostPlacedOrderPlacedOrderItemsPageExportBatchData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        search?: string;
        skuId?: string;
        sort?: string;
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/placed-order-items/export-batch';
};

export type PostPlacedOrderPlacedOrderItemsPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetPlacedOrderItemByExternalReferenceCodePlacedOrderItemShipmentsPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-order-items/by-externalReferenceCode/{externalReferenceCode}/placed-order-item-shipments';
};

export type GetPlacedOrderItemByExternalReferenceCodePlacedOrderItemShipmentsPageResponses = {
    /**
     * default response
     */
    default: PagePlacedOrderItemShipment;
};

export type GetPlacedOrderItemByExternalReferenceCodePlacedOrderItemShipmentsPageResponse = GetPlacedOrderItemByExternalReferenceCodePlacedOrderItemShipmentsPageResponses[keyof GetPlacedOrderItemByExternalReferenceCodePlacedOrderItemShipmentsPageResponses];

export type GetPlacedOrderItemPlacedOrderItemShipmentsPageData = {
    body?: never;
    path: {
        placedOrderItemId: string;
    };
    query?: {
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-order-items/{placedOrderItemId}/placed-order-item-shipments';
};

export type GetPlacedOrderItemPlacedOrderItemShipmentsPageResponses = {
    /**
     * default response
     */
    default: PagePlacedOrderItemShipment;
};

export type GetPlacedOrderItemPlacedOrderItemShipmentsPageResponse = GetPlacedOrderItemPlacedOrderItemShipmentsPageResponses[keyof GetPlacedOrderItemPlacedOrderItemShipmentsPageResponses];

export type PostPlacedOrderItemPlacedOrderItemShipmentsPageExportBatchData = {
    body?: never;
    path: {
        placedOrderItemId: string;
    };
    query?: {
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-order-items/{placedOrderItemId}/placed-order-item-shipments/export-batch';
};

export type PostPlacedOrderItemPlacedOrderItemShipmentsPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetChannelAccountPlacedOrdersPageData = {
    body?: never;
    path: {
        accountId: string;
        channelId: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/channels/{channelId}/accounts/{accountId}/placed-orders';
};

export type GetChannelAccountPlacedOrdersPageResponses = {
    /**
     * default response
     */
    default: PagePlacedOrder;
};

export type GetChannelAccountPlacedOrdersPageResponse = GetChannelAccountPlacedOrdersPageResponses[keyof GetChannelAccountPlacedOrdersPageResponses];

export type GetChannelByExternalReferenceCodeChannelExternalReferenceCodeAccountByExternalReferenceCodeAccountExternalReferenceCodePlacedOrdersPageData = {
    body?: never;
    path: {
        accountExternalReferenceCode: string;
        channelExternalReferenceCode: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/channels/by-externalReferenceCode/{channelExternalReferenceCode}/accounts/by-externalReferenceCode/{accountExternalReferenceCode}/placed-orders';
};

export type GetChannelByExternalReferenceCodeChannelExternalReferenceCodeAccountByExternalReferenceCodeAccountExternalReferenceCodePlacedOrdersPageResponses = {
    /**
     * default response
     */
    default: PagePlacedOrder;
};

export type GetChannelByExternalReferenceCodeChannelExternalReferenceCodeAccountByExternalReferenceCodeAccountExternalReferenceCodePlacedOrdersPageResponse = GetChannelByExternalReferenceCodeChannelExternalReferenceCodeAccountByExternalReferenceCodeAccountExternalReferenceCodePlacedOrdersPageResponses[keyof GetChannelByExternalReferenceCodeChannelExternalReferenceCodeAccountByExternalReferenceCodeAccountExternalReferenceCodePlacedOrdersPageResponses];

export type GetChannelByExternalReferenceCodePlacedOrdersPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/channels/by-externalReferenceCode/{externalReferenceCode}/placed-orders';
};

export type GetChannelByExternalReferenceCodePlacedOrdersPageResponses = {
    /**
     * default response
     */
    default: PagePlacedOrder;
};

export type GetChannelByExternalReferenceCodePlacedOrdersPageResponse = GetChannelByExternalReferenceCodePlacedOrdersPageResponses[keyof GetChannelByExternalReferenceCodePlacedOrdersPageResponses];

export type GetChannelPlacedOrdersPageData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/channels/{channelId}/placed-orders';
};

export type GetChannelPlacedOrdersPageResponses = {
    /**
     * default response
     */
    default: PagePlacedOrder;
};

export type GetChannelPlacedOrdersPageResponse = GetChannelPlacedOrdersPageResponses[keyof GetChannelPlacedOrdersPageResponses];

export type GetPlacedOrderData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}';
};

export type GetPlacedOrderResponses = {
    /**
     * default response
     */
    default: PlacedOrder;
};

export type GetPlacedOrderResponse = GetPlacedOrderResponses[keyof GetPlacedOrderResponses];

export type PatchPlacedOrderData = {
    body?: PlacedOrder;
    path: {
        placedOrderId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}';
};

export type PatchPlacedOrderResponses = {
    /**
     * default response
     */
    default: PlacedOrder;
};

export type PatchPlacedOrderResponse = PatchPlacedOrderResponses[keyof PatchPlacedOrderResponses];

export type GetPlacedOrderByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}';
};

export type GetPlacedOrderByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: PlacedOrder;
};

export type GetPlacedOrderByExternalReferenceCodeResponse = GetPlacedOrderByExternalReferenceCodeResponses[keyof GetPlacedOrderByExternalReferenceCodeResponses];

export type PatchPlacedOrderByExternalReferenceCodeData = {
    body?: PlacedOrder;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}';
};

export type PatchPlacedOrderByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: PlacedOrder;
};

export type PatchPlacedOrderByExternalReferenceCodeResponse = PatchPlacedOrderByExternalReferenceCodeResponses[keyof PatchPlacedOrderByExternalReferenceCodeResponses];

export type GetPlacedOrderByExternalReferenceCodePaymentUrlData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/payment-url';
};

export type GetPlacedOrderByExternalReferenceCodePaymentUrlResponses = {
    /**
     * default response
     */
    default: string;
};

export type GetPlacedOrderByExternalReferenceCodePaymentUrlResponse = GetPlacedOrderByExternalReferenceCodePaymentUrlResponses[keyof GetPlacedOrderByExternalReferenceCodePaymentUrlResponses];

export type GetPlacedOrderPaymentUrlData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/payment-url';
};

export type GetPlacedOrderPaymentUrlResponses = {
    /**
     * default response
     */
    default: string;
};

export type GetPlacedOrderPaymentUrlResponse = GetPlacedOrderPaymentUrlResponses[keyof GetPlacedOrderPaymentUrlResponses];

export type GetPlacedOrderByExternalReferenceCodeShipmentsPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/shipments';
};

export type GetPlacedOrderByExternalReferenceCodeShipmentsPageResponses = {
    /**
     * default response
     */
    default: PageShipment;
};

export type GetPlacedOrderByExternalReferenceCodeShipmentsPageResponse = GetPlacedOrderByExternalReferenceCodeShipmentsPageResponses[keyof GetPlacedOrderByExternalReferenceCodeShipmentsPageResponses];

export type GetPlacedOrderShipmentsPageData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/shipments';
};

export type GetPlacedOrderShipmentsPageResponses = {
    /**
     * default response
     */
    default: PageShipment;
};

export type GetPlacedOrderShipmentsPageResponse = GetPlacedOrderShipmentsPageResponses[keyof GetPlacedOrderShipmentsPageResponses];

export type PostPlacedOrderShipmentsPageExportBatchData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: {
        filter?: string;
        search?: string;
        sort?: string;
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/shipments/export-batch';
};

export type PostPlacedOrderShipmentsPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetPlacedOrderByExternalReferenceCodeDeliveryTermData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/delivery-term';
};

export type GetPlacedOrderByExternalReferenceCodeDeliveryTermResponses = {
    /**
     * default response
     */
    default: Term;
};

export type GetPlacedOrderByExternalReferenceCodeDeliveryTermResponse = GetPlacedOrderByExternalReferenceCodeDeliveryTermResponses[keyof GetPlacedOrderByExternalReferenceCodeDeliveryTermResponses];

export type GetPlacedOrderByExternalReferenceCodePaymentTermData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/by-externalReferenceCode/{externalReferenceCode}/payment-term';
};

export type GetPlacedOrderByExternalReferenceCodePaymentTermResponses = {
    /**
     * default response
     */
    default: Term;
};

export type GetPlacedOrderByExternalReferenceCodePaymentTermResponse = GetPlacedOrderByExternalReferenceCodePaymentTermResponses[keyof GetPlacedOrderByExternalReferenceCodePaymentTermResponses];

export type GetPlacedOrderDeliveryTermData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/delivery-term';
};

export type GetPlacedOrderDeliveryTermResponses = {
    /**
     * default response
     */
    default: Term;
};

export type GetPlacedOrderDeliveryTermResponse = GetPlacedOrderDeliveryTermResponses[keyof GetPlacedOrderDeliveryTermResponses];

export type GetPlacedOrderPaymentTermData = {
    body?: never;
    path: {
        placedOrderId: string;
    };
    query?: never;
    url: '/o/headless-commerce-delivery-order/v1.0/placed-orders/{placedOrderId}/payment-term';
};

export type GetPlacedOrderPaymentTermResponses = {
    /**
     * default response
     */
    default: Term;
};

export type GetPlacedOrderPaymentTermResponse = GetPlacedOrderPaymentTermResponses[keyof GetPlacedOrderPaymentTermResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};