// This file is auto-generated by @hey-api/openapi-ts

export type DispatchTriggerReadable = {
    active?: boolean;
    companyId?: number;
    cronExpression?: string;
    dispatchTaskClusterMode?: number;
    dispatchTaskExecutorType?: string;
    dispatchTaskSettings?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    readonly endDate?: string;
    externalReferenceCode?: string;
    id?: number;
    name?: string;
    overlapAllowed?: boolean;
    readonly startDate?: string;
    system?: boolean;
    timeZoneId?: string;
    userId?: number;
    readonly 'x-class-name'?: string;
};

export type DispatchTriggerWritable = {
    active?: boolean;
    companyId?: number;
    cronExpression?: string;
    dispatchTaskClusterMode?: number;
    dispatchTaskExecutorType?: string;
    dispatchTaskSettings?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    externalReferenceCode?: string;
    id?: number;
    name?: string;
    overlapAllowed?: boolean;
    system?: boolean;
    timeZoneId?: string;
    userId?: number;
};

export type Facet = {
    facetCriteria?: string;
    facetValues?: Array<FacetValue>;
};

export type FacetValue = {
    numberOfOccurrences?: number;
    term?: string;
};

export type PageDispatchTriggerReadable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<DispatchTriggerReadable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PageDispatchTriggerWritable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<DispatchTriggerWritable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type GetDispatchTriggersPageData = {
    body?: never;
    path?: never;
    query?: {
        nestedFields?: string;
    };
    url: '/o/dispatch-rest/v1.0/dispatch-triggers';
};

export type GetDispatchTriggersPageResponses = {
    /**
     * default response
     */
    default: PageDispatchTriggerReadable;
};

export type GetDispatchTriggersPageResponse = GetDispatchTriggersPageResponses[keyof GetDispatchTriggersPageResponses];

export type PostDispatchTriggerData = {
    body?: DispatchTriggerWritable;
    path?: never;
    query?: never;
    url: '/o/dispatch-rest/v1.0/dispatch-triggers';
};

export type PostDispatchTriggerResponses = {
    /**
     * default response
     */
    default: DispatchTriggerReadable;
};

export type PostDispatchTriggerResponse = PostDispatchTriggerResponses[keyof PostDispatchTriggerResponses];

export type PostDispatchTriggerBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/dispatch-rest/v1.0/dispatch-triggers/batch';
};

export type PostDispatchTriggerBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostDispatchTriggerRunData = {
    body?: never;
    path: {
        dispatchTriggerId: string;
    };
    query?: never;
    url: '/o/dispatch-rest/v1.0/dispatch-triggers/{dispatchTriggerId}/run';
};

export type PostDispatchTriggerRunResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostDispatchTriggersPageExportBatchData = {
    body?: never;
    path?: never;
    query?: {
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/dispatch-rest/v1.0/dispatch-triggers/export-batch';
};

export type PostDispatchTriggersPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};