// This file is auto-generated by @hey-api/openapi-ts

export type AccountCategoryForecastReadable = {
    account?: number;
    actual?: number;
    category?: number;
    categoryTitle?: string;
    forecast?: number;
    forecastLowerBound?: number;
    forecastUpperBound?: number;
    timestamp?: string;
    unit?: string;
    readonly 'x-class-name'?: string;
};

export type AccountCategoryForecastWritable = {
    account?: number;
    actual?: number;
    category?: number;
    categoryTitle?: string;
    forecast?: number;
    forecastLowerBound?: number;
    forecastUpperBound?: number;
    timestamp?: string;
    unit?: string;
};

export type Facet = {
    facetCriteria?: string;
    facetValues?: Array<FacetValue>;
};

export type FacetValue = {
    numberOfOccurrences?: number;
    term?: string;
};

export type PageAccountCategoryForecastReadable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<AccountCategoryForecastReadable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PageAccountCategoryForecastWritable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<AccountCategoryForecastWritable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type AccountForecastReadable = {
    account?: number;
    actual?: number;
    forecast?: number;
    forecastLowerBound?: number;
    forecastUpperBound?: number;
    timestamp?: string;
    unit?: string;
    readonly 'x-class-name'?: string;
};

export type AccountForecastWritable = {
    account?: number;
    actual?: number;
    forecast?: number;
    forecastLowerBound?: number;
    forecastUpperBound?: number;
    timestamp?: string;
    unit?: string;
};

export type PageAccountForecastReadable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<AccountForecastReadable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PageAccountForecastWritable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<AccountForecastWritable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PageSkuForecastReadable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<SkuForecastReadable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PageSkuForecastWritable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<SkuForecastWritable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type SkuForecastReadable = {
    actual?: number;
    forecast?: number;
    forecastLowerBound?: number;
    forecastUpperBound?: number;
    sku?: string;
    timestamp?: string;
    unit?: string;
    readonly 'x-class-name'?: string;
};

export type SkuForecastWritable = {
    actual?: number;
    forecast?: number;
    forecastLowerBound?: number;
    forecastUpperBound?: number;
    sku?: string;
    timestamp?: string;
    unit?: string;
};

export type GetAccountCategoryForecastsByMonthlyRevenuePageData = {
    body?: never;
    path?: never;
    query?: {
        accountIds?: string;
        categoryIds?: string;
        forecastLength?: string;
        forecastStartDate?: string;
        historyLength?: string;
        page?: string;
        pageSize?: string;
    };
    url: '/v1.0/accountCategoryForecasts/by-monthlyRevenue';
};

export type GetAccountCategoryForecastsByMonthlyRevenuePageResponses = {
    /**
     * default response
     */
    default: PageAccountCategoryForecastReadable;
};

export type GetAccountCategoryForecastsByMonthlyRevenuePageResponse = GetAccountCategoryForecastsByMonthlyRevenuePageResponses[keyof GetAccountCategoryForecastsByMonthlyRevenuePageResponses];

export type GetAccountForecastsByMonthlyRevenuePageData = {
    body?: never;
    path?: never;
    query?: {
        accountIds?: string;
        forecastLength?: string;
        forecastStartDate?: string;
        historyLength?: string;
        page?: string;
        pageSize?: string;
    };
    url: '/v1.0/accountForecasts/by-monthlyRevenue';
};

export type GetAccountForecastsByMonthlyRevenuePageResponses = {
    /**
     * default response
     */
    default: PageAccountForecastReadable;
};

export type GetAccountForecastsByMonthlyRevenuePageResponse = GetAccountForecastsByMonthlyRevenuePageResponses[keyof GetAccountForecastsByMonthlyRevenuePageResponses];

export type GetOpenApiData = {
    body?: never;
    path: {
        type: string;
    };
    query?: never;
    url: '/v1.0/openapi.{type}';
};

export type GetOpenApiResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetSkuForecastsByMonthlyRevenuePageData = {
    body?: never;
    path?: never;
    query?: {
        forecastLength?: string;
        forecastStartDate?: string;
        historyLength?: string;
        page?: string;
        pageSize?: string;
        skus?: string;
    };
    url: '/v1.0/skuForecasts/by-monthlyDemand';
};

export type GetSkuForecastsByMonthlyRevenuePageResponses = {
    /**
     * default response
     */
    default: PageSkuForecastReadable;
};

export type GetSkuForecastsByMonthlyRevenuePageResponse = GetSkuForecastsByMonthlyRevenuePageResponses[keyof GetSkuForecastsByMonthlyRevenuePageResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/o/headless-commerce-machine-learning/' | (string & {});
};