// This file is auto-generated by @hey-api/openapi-ts

export type Payment = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    amount?: number;
    readonly amountFormatted?: string;
    readonly author?: string;
    callbackURL?: string;
    cancelURL?: string;
    channelId?: number;
    comment?: string;
    readonly createDate?: string;
    currencyCode?: string;
    currencyExternalReferenceCode?: string;
    currencyId?: number;
    errorMessages?: string;
    externalReferenceCode?: string;
    readonly id?: number;
    languageId?: string;
    payload?: string;
    paymentIntegrationKey?: string;
    paymentIntegrationType?: number;
    paymentStatus?: number;
    paymentStatusStatus?: Status;
    reasonKey?: string;
    readonly reasonName?: {
        [key: string]: string;
    };
    redirectURL?: string;
    relatedItemId?: number;
    relatedItemName?: string;
    relatedItemNameLabel?: string;
    transactionCode?: string;
    type?: number;
    readonly typeLabel?: string;
    readonly 'x-class-name'?: string;
};

export type Status = {
    readonly code?: number;
    label?: string;
    label_i18n?: string;
    readonly 'x-class-name'?: string;
};

export type Facet = {
    facetCriteria?: string;
    facetValues?: Array<FacetValue>;
};

export type FacetValue = {
    numberOfOccurrences?: number;
    term?: string;
};

export type PagePayment = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<Payment>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type DeletePaymentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-payment/v1.0/payments/{id}';
};

export type DeletePaymentResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetPaymentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-payment/v1.0/payments/{id}';
};

export type GetPaymentResponses = {
    /**
     * default response
     */
    default: Payment;
};

export type GetPaymentResponse = GetPaymentResponses[keyof GetPaymentResponses];

export type PatchPaymentData = {
    body?: Payment;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-payment/v1.0/payments/{id}';
};

export type PatchPaymentResponses = {
    /**
     * default response
     */
    default: Payment;
};

export type PatchPaymentResponse = PatchPaymentResponses[keyof PatchPaymentResponses];

export type DeletePaymentBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-payment/v1.0/payments/batch';
};

export type DeletePaymentBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostPaymentBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/headless-commerce-admin-payment/v1.0/payments/batch';
};

export type PostPaymentBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeletePaymentByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-payment/v1.0/payments/by-externalReferenceCode/{externalReferenceCode}';
};

export type DeletePaymentByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetPaymentByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-payment/v1.0/payments/by-externalReferenceCode/{externalReferenceCode}';
};

export type GetPaymentByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: Payment;
};

export type GetPaymentByExternalReferenceCodeResponse = GetPaymentByExternalReferenceCodeResponses[keyof GetPaymentByExternalReferenceCodeResponses];

export type PatchPaymentByExternalReferenceCodeData = {
    body?: Payment;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-payment/v1.0/payments/by-externalReferenceCode/{externalReferenceCode}';
};

export type PatchPaymentByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: Payment;
};

export type PatchPaymentByExternalReferenceCodeResponse = PatchPaymentByExternalReferenceCodeResponses[keyof PatchPaymentByExternalReferenceCodeResponses];

export type PutPaymentByExternalReferenceCodeData = {
    body?: Payment;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-payment/v1.0/payments/by-externalReferenceCode/{externalReferenceCode}';
};

export type PutPaymentByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: Payment;
};

export type PutPaymentByExternalReferenceCodeResponse = PutPaymentByExternalReferenceCodeResponses[keyof PutPaymentByExternalReferenceCodeResponses];

export type GetPaymentsPageData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/headless-commerce-admin-payment/v1.0/payments';
};

export type GetPaymentsPageResponses = {
    /**
     * default response
     */
    default: PagePayment;
};

export type GetPaymentsPageResponse = GetPaymentsPageResponses[keyof GetPaymentsPageResponses];

export type PostPaymentData = {
    body?: Payment;
    path?: never;
    query?: never;
    url: '/o/headless-commerce-admin-payment/v1.0/payments';
};

export type PostPaymentResponses = {
    /**
     * default response
     */
    default: Payment;
};

export type PostPaymentResponse = PostPaymentResponses[keyof PostPaymentResponses];

export type PostPaymentByExternalReferenceCodeRefundData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-payment/v1.0/payments/by-externalReferenceCode/{externalReferenceCode}/refund';
};

export type PostPaymentByExternalReferenceCodeRefundResponses = {
    /**
     * default response
     */
    default: Payment;
};

export type PostPaymentByExternalReferenceCodeRefundResponse = PostPaymentByExternalReferenceCodeRefundResponses[keyof PostPaymentByExternalReferenceCodeRefundResponses];

export type PostPaymentRefundData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/headless-commerce-admin-payment/v1.0/payments/{id}/refund';
};

export type PostPaymentRefundResponses = {
    /**
     * default response
     */
    default: Payment;
};

export type PostPaymentRefundResponse = PostPaymentRefundResponses[keyof PostPaymentRefundResponses];

export type PostPaymentsPageExportBatchData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        search?: string;
        sort?: string;
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/headless-commerce-admin-payment/v1.0/payments/export-batch';
};

export type PostPaymentsPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};