// This file is auto-generated by @hey-api/openapi-ts

export type CtCollection = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    /**
     * The publication's creation date.
     */
    readonly dateCreated?: string;
    /**
     * The last time any of the publication's fields were changed.
     */
    readonly dateModified?: string;
    /**
     * The date that the publication will be published.
     */
    readonly dateScheduled?: string;
    description?: string;
    externalReferenceCode?: string;
    readonly id?: number;
    name?: string;
    /**
     * The publication's creator.
     */
    readonly ownerName?: string;
    status?: Status;
    /**
     * Info on when a publication was last published or modified.
     */
    readonly statusMessage?: string;
    readonly 'x-class-name'?: string;
};

export type Status = {
    code?: number;
    label?: string;
    label_i18n?: string;
    readonly 'x-class-name'?: string;
};

export type Facet = {
    facetCriteria?: string;
    facetValues?: Array<FacetValue>;
};

export type FacetValue = {
    numberOfOccurrences?: number;
    term?: string;
};

export type PageCtCollection = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<CtCollection>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type CtEntry = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    readonly changeType?: string;
    readonly ctCollectionId?: number;
    readonly ctCollectionName?: string;
    ctCollectionStatus?: Status;
    readonly ctCollectionStatusDate?: string;
    readonly ctCollectionStatusUserName?: string;
    readonly dateCreated?: string;
    readonly dateModified?: string;
    readonly hideable?: boolean;
    readonly id?: number;
    readonly modelClassNameId?: number;
    readonly modelClassPK?: number;
    readonly ownerId?: number;
    readonly ownerName?: string;
    readonly siteId?: number;
    readonly siteName?: string;
    status?: Status;
    /**
     * Info on when a change was made.
     */
    readonly statusMessage?: string;
    readonly title?: string;
    readonly typeName?: string;
    readonly 'x-class-name'?: string;
};

export type PageCtEntry = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<CtEntry>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type CtProcess = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    readonly ctCollectionId?: number;
    /**
     * The publication's published date.
     */
    readonly datePublished?: string;
    description?: string;
    readonly id?: number;
    name?: string;
    /**
     * The publication's creator.
     */
    readonly ownerName?: string;
    status?: Status;
    readonly 'x-class-name'?: string;
};

export type PageCtProcess = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<CtProcess>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type CtRemote = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    clientId?: string;
    clientSecret?: string;
    /**
     * The remote's creation date.
     */
    readonly dateCreated?: string;
    /**
     * The last time any of the remote's fields were changed.
     */
    readonly dateModified?: string;
    description?: string;
    readonly id?: number;
    name?: string;
    /**
     * The remote's creator.
     */
    readonly ownerName?: string;
    url?: string;
    readonly 'x-class-name'?: string;
};

export type PageCtRemote = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<CtRemote>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type DeleteCtCollectionData = {
    body?: never;
    path: {
        ctCollectionId: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/{ctCollectionId}';
};

export type DeleteCtCollectionResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetCtCollectionData = {
    body?: never;
    path: {
        ctCollectionId: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/{ctCollectionId}';
};

export type GetCtCollectionResponses = {
    /**
     * default response
     */
    default: CtCollection;
};

export type GetCtCollectionResponse = GetCtCollectionResponses[keyof GetCtCollectionResponses];

export type PatchCtCollectionData = {
    body?: CtCollection;
    path: {
        ctCollectionId: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/{ctCollectionId}';
};

export type PatchCtCollectionResponses = {
    /**
     * default response
     */
    default: CtCollection;
};

export type PatchCtCollectionResponse = PatchCtCollectionResponses[keyof PatchCtCollectionResponses];

export type PutCtCollectionData = {
    body?: CtCollection;
    path: {
        ctCollectionId: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/{ctCollectionId}';
};

export type PutCtCollectionResponses = {
    /**
     * default response
     */
    default: CtCollection;
};

export type PutCtCollectionResponse = PutCtCollectionResponses[keyof PutCtCollectionResponses];

export type DeleteCtCollectionBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-collections/batch';
};

export type DeleteCtCollectionBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostCtCollectionBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-collections/batch';
};

export type PostCtCollectionBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PutCtCollectionBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-collections/batch';
};

export type PutCtCollectionBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteCtCollectionByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/by-external-reference-code/{externalReferenceCode}';
};

export type DeleteCtCollectionByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetCtCollectionByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/by-external-reference-code/{externalReferenceCode}';
};

export type GetCtCollectionByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: CtCollection;
};

export type GetCtCollectionByExternalReferenceCodeResponse = GetCtCollectionByExternalReferenceCodeResponses[keyof GetCtCollectionByExternalReferenceCodeResponses];

export type PatchCtCollectionByExternalReferenceCodeData = {
    body?: CtCollection;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/by-external-reference-code/{externalReferenceCode}';
};

export type PatchCtCollectionByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: CtCollection;
};

export type PatchCtCollectionByExternalReferenceCodeResponse = PatchCtCollectionByExternalReferenceCodeResponses[keyof PatchCtCollectionByExternalReferenceCodeResponses];

export type GetCtCollectionByExternalReferenceCodeShareLinkData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/by-external-reference-code/{externalReferenceCode}/share-link';
};

export type GetCtCollectionByExternalReferenceCodeShareLinkResponses = {
    /**
     * default response
     */
    default: string;
};

export type GetCtCollectionByExternalReferenceCodeShareLinkResponse = GetCtCollectionByExternalReferenceCodeShareLinkResponses[keyof GetCtCollectionByExternalReferenceCodeShareLinkResponses];

export type GetCtCollectionShareLinkData = {
    body?: never;
    path: {
        ctCollectionId: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/b{ctCollectionId}/share-link';
};

export type GetCtCollectionShareLinkResponses = {
    /**
     * default response
     */
    default: string;
};

export type GetCtCollectionShareLinkResponse = GetCtCollectionShareLinkResponses[keyof GetCtCollectionShareLinkResponses];

export type GetCtCollectionsPageData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        status?: string;
        nestedFields?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-collections';
};

export type GetCtCollectionsPageResponses = {
    /**
     * default response
     */
    default: PageCtCollection;
};

export type GetCtCollectionsPageResponse = GetCtCollectionsPageResponses[keyof GetCtCollectionsPageResponses];

export type PostCtCollectionData = {
    body?: CtCollection;
    path?: never;
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections';
};

export type PostCtCollectionResponses = {
    /**
     * default response
     */
    default: CtCollection;
};

export type PostCtCollectionResponse = PostCtCollectionResponses[keyof PostCtCollectionResponses];

export type PostCtCollectionByExternalReferenceCodePublishData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/by-external-reference-code/{externalReferenceCode}/publish';
};

export type PostCtCollectionByExternalReferenceCodePublishResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostCtCollectionByExternalReferenceCodeSchedulePublishData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        publishDate?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-collections/by-external-reference-code/{externalReferenceCode}/schedule-publish';
};

export type PostCtCollectionByExternalReferenceCodeSchedulePublishResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostCtCollectionCheckoutData = {
    body?: never;
    path: {
        ctCollectionId: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/{ctCollectionId}/checkout';
};

export type PostCtCollectionCheckoutResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostCtCollectionPublishData = {
    body?: never;
    path: {
        ctCollectionId: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/{ctCollectionId}/publish';
};

export type PostCtCollectionPublishResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostCtCollectionSchedulePublishData = {
    body?: never;
    path: {
        ctCollectionId: string;
    };
    query?: {
        publishDate?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-collections/{ctCollectionId}/schedule-publish';
};

export type PostCtCollectionSchedulePublishResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostCtCollectionsPageExportBatchData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        sort?: string;
        status?: string;
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-collections/export-batch';
};

export type PostCtCollectionsPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetCtEntriesHistoryPageData = {
    body?: never;
    path?: never;
    query?: {
        classNameId?: string;
        classPK?: string;
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        siteId?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-entries/history';
};

export type GetCtEntriesHistoryPageResponses = {
    /**
     * default response
     */
    default: PageCtEntry;
};

export type GetCtEntriesHistoryPageResponse = GetCtEntriesHistoryPageResponses[keyof GetCtEntriesHistoryPageResponses];

export type GetCtEntryData = {
    body?: never;
    path: {
        ctEntryId: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-entries/{ctEntryId}';
};

export type GetCtEntryResponses = {
    /**
     * default response
     */
    default: CtEntry;
};

export type GetCtEntryResponse = GetCtEntryResponses[keyof GetCtEntryResponses];

export type GetCtCollectionCtEntriesPageData = {
    body?: never;
    path: {
        ctCollectionId: string;
    };
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        showHideable?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-collections/{ctCollectionId}/ct-entries';
};

export type GetCtCollectionCtEntriesPageResponses = {
    /**
     * default response
     */
    default: PageCtEntry;
};

export type GetCtCollectionCtEntriesPageResponse = GetCtCollectionCtEntriesPageResponses[keyof GetCtCollectionCtEntriesPageResponses];

export type GetCtCollectionCtEntryByModelClassNameByModelClassPkModelClassPkData = {
    body?: never;
    path: {
        ctCollectionId: string;
        modelClassNameId: string;
        modelClassPK: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-collections/{ctCollectionId}/ct-entries/by-model-class-name-id/{modelClassNameId}/by-model-class-pk/{modelClassPK}';
};

export type GetCtCollectionCtEntryByModelClassNameByModelClassPkModelClassPkResponses = {
    /**
     * default response
     */
    default: CtEntry;
};

export type GetCtCollectionCtEntryByModelClassNameByModelClassPkModelClassPkResponse = GetCtCollectionCtEntryByModelClassNameByModelClassPkModelClassPkResponses[keyof GetCtCollectionCtEntryByModelClassNameByModelClassPkModelClassPkResponses];

export type DeleteCtProcessData = {
    body?: never;
    path: {
        ctProcessId: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-processes/{ctProcessId}';
};

export type DeleteCtProcessResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetCtProcessData = {
    body?: never;
    path: {
        ctProcessId: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-processes/{ctProcessId}';
};

export type GetCtProcessResponses = {
    /**
     * default response
     */
    default: CtProcess;
};

export type GetCtProcessResponse = GetCtProcessResponses[keyof GetCtProcessResponses];

export type DeleteCtProcessBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-processes/batch';
};

export type DeleteCtProcessBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetCtProcessesPageData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        status?: string;
        nestedFields?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-processes';
};

export type GetCtProcessesPageResponses = {
    /**
     * default response
     */
    default: PageCtProcess;
};

export type GetCtProcessesPageResponse = GetCtProcessesPageResponses[keyof GetCtProcessesPageResponses];

export type PostCtProcessRevertData = {
    body?: never;
    path: {
        ctProcessId: string;
    };
    query?: {
        description?: string;
        name?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-processes/{ctProcessId}/revert';
};

export type PostCtProcessRevertResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostCtProcessesPageExportBatchData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        search?: string;
        sort?: string;
        status?: string;
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-processes/export-batch';
};

export type PostCtProcessesPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteCtRemoteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-remotes/{id}';
};

export type DeleteCtRemoteResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetCtRemoteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-remotes/{id}';
};

export type GetCtRemoteResponses = {
    /**
     * default response
     */
    default: CtRemote;
};

export type GetCtRemoteResponse = GetCtRemoteResponses[keyof GetCtRemoteResponses];

export type PatchCtRemoteData = {
    body?: CtRemote;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-remotes/{id}';
};

export type PatchCtRemoteResponses = {
    /**
     * default response
     */
    default: CtRemote;
};

export type PatchCtRemoteResponse = PatchCtRemoteResponses[keyof PatchCtRemoteResponses];

export type PutCtRemoteData = {
    body?: CtRemote;
    path: {
        id: string;
    };
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-remotes/{id}';
};

export type PutCtRemoteResponses = {
    /**
     * default response
     */
    default: CtRemote;
};

export type PutCtRemoteResponse = PutCtRemoteResponses[keyof PutCtRemoteResponses];

export type DeleteCtRemoteBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-remotes/batch';
};

export type DeleteCtRemoteBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostCtRemoteBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-remotes/batch';
};

export type PostCtRemoteBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PutCtRemoteBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-remotes/batch';
};

export type PutCtRemoteBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetCtRemotesPageData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-remotes';
};

export type GetCtRemotesPageResponses = {
    /**
     * default response
     */
    default: PageCtRemote;
};

export type GetCtRemotesPageResponse = GetCtRemotesPageResponses[keyof GetCtRemotesPageResponses];

export type PostCtRemoteData = {
    body?: CtRemote;
    path?: never;
    query?: never;
    url: '/o/change-tracking-rest/v1.0/ct-remotes';
};

export type PostCtRemoteResponses = {
    /**
     * default response
     */
    default: CtRemote;
};

export type PostCtRemoteResponse = PostCtRemoteResponses[keyof PostCtRemoteResponses];

export type PostCtRemotesPageExportBatchData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        sort?: string;
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/change-tracking-rest/v1.0/ct-remotes/export-batch';
};

export type PostCtRemotesPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};