// This file is auto-generated by @hey-api/openapi-ts

export type Facet = {
    facetCriteria?: string;
    facetValues?: Array<FacetValue>;
};

export type FacetValue = {
    numberOfOccurrences?: number;
    term?: string;
};

export type NotificationQueueEntry = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    body?: string;
    readonly fromName?: string;
    readonly id?: number;
    recipients?: Array<{
        [key: string]: unknown;
    }>;
    readonly recipientsSummary?: string;
    readonly sentDate?: string;
    readonly status?: number;
    subject?: string;
    readonly triggerBy?: string;
    type?: string;
    readonly typeLabel?: string;
    readonly 'x-class-name'?: string;
};

export type PageNotificationQueueEntry = {
    totalCount?: number;
    lastPage?: number;
    items?: Array<NotificationQueueEntry>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type NotificationTemplate = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    attachmentObjectFieldExternalReferenceCodes?: Array<string>;
    attachmentObjectFieldIds?: Array<number>;
    body?: {
        [key: string]: string;
    };
    readonly dateCreated?: string;
    readonly dateModified?: string;
    description?: string;
    externalReferenceCode?: string;
    readonly id?: number;
    name?: string;
    name_i18n?: {
        [key: string]: string;
    };
    objectDefinitionExternalReferenceCode?: string;
    objectDefinitionId?: number;
    recipientType?: string;
    recipients?: Array<{
        [key: string]: unknown;
    }>;
    subject?: {
        [key: string]: string;
    };
    system?: boolean;
    type?: string;
    typeLabel?: string;
    readonly 'x-class-name'?: string;
    editorType?: 'freeMarker' | 'richText';
};

export type PageNotificationTemplate = {
    totalCount?: number;
    lastPage?: number;
    items?: Array<NotificationTemplate>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type DeleteNotificationQueueEntryData = {
    body?: never;
    path: {
        notificationQueueEntryId: string;
    };
    query?: never;
    url: '/o/notification/v1.0/notification-queue-entries/{notificationQueueEntryId}';
};

export type DeleteNotificationQueueEntryResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetNotificationQueueEntryData = {
    body?: never;
    path: {
        notificationQueueEntryId: string;
    };
    query?: never;
    url: '/o/notification/v1.0/notification-queue-entries/{notificationQueueEntryId}';
};

export type GetNotificationQueueEntryResponses = {
    /**
     * default response
     */
    default: NotificationQueueEntry;
};

export type GetNotificationQueueEntryResponse = GetNotificationQueueEntryResponses[keyof GetNotificationQueueEntryResponses];

export type DeleteNotificationQueueEntryBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/notification/v1.0/notification-queue-entries/batch';
};

export type DeleteNotificationQueueEntryBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostNotificationQueueEntryBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/notification/v1.0/notification-queue-entries/batch';
};

export type PostNotificationQueueEntryBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetNotificationQueueEntriesPageData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/notification/v1.0/notification-queue-entries';
};

export type GetNotificationQueueEntriesPageResponses = {
    /**
     * default response
     */
    default: PageNotificationQueueEntry;
};

export type GetNotificationQueueEntriesPageResponse = GetNotificationQueueEntriesPageResponses[keyof GetNotificationQueueEntriesPageResponses];

export type PostNotificationQueueEntryData = {
    body?: NotificationQueueEntry;
    path?: never;
    query?: never;
    url: '/o/notification/v1.0/notification-queue-entries';
};

export type PostNotificationQueueEntryResponses = {
    /**
     * default response
     */
    default: NotificationQueueEntry;
};

export type PostNotificationQueueEntryResponse = PostNotificationQueueEntryResponses[keyof PostNotificationQueueEntryResponses];

export type PostNotificationQueueEntriesPageExportBatchData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        search?: string;
        sort?: string;
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/notification/v1.0/notification-queue-entries/export-batch';
};

export type PostNotificationQueueEntriesPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PutNotificationQueueEntryResendData = {
    body?: never;
    path: {
        notificationQueueEntryId: string;
    };
    query?: never;
    url: '/o/notification/v1.0/notification-queue-entries/{notificationQueueEntryId}/resend';
};

export type PutNotificationQueueEntryResendResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteNotificationTemplateData = {
    body?: never;
    path: {
        notificationTemplateId: string;
    };
    query?: never;
    url: '/o/notification/v1.0/notification-templates/{notificationTemplateId}';
};

export type DeleteNotificationTemplateResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetNotificationTemplateData = {
    body?: never;
    path: {
        notificationTemplateId: string;
    };
    query?: never;
    url: '/o/notification/v1.0/notification-templates/{notificationTemplateId}';
};

export type GetNotificationTemplateResponses = {
    /**
     * default response
     */
    default: NotificationTemplate;
};

export type GetNotificationTemplateResponse = GetNotificationTemplateResponses[keyof GetNotificationTemplateResponses];

export type PatchNotificationTemplateData = {
    body?: NotificationTemplate;
    path: {
        notificationTemplateId: string;
    };
    query?: never;
    url: '/o/notification/v1.0/notification-templates/{notificationTemplateId}';
};

export type PatchNotificationTemplateResponses = {
    /**
     * default response
     */
    default: NotificationTemplate;
};

export type PatchNotificationTemplateResponse = PatchNotificationTemplateResponses[keyof PatchNotificationTemplateResponses];

export type PutNotificationTemplateData = {
    body?: NotificationTemplate;
    path: {
        notificationTemplateId: string;
    };
    query?: never;
    url: '/o/notification/v1.0/notification-templates/{notificationTemplateId}';
};

export type PutNotificationTemplateResponses = {
    /**
     * default response
     */
    default: NotificationTemplate;
};

export type PutNotificationTemplateResponse = PutNotificationTemplateResponses[keyof PutNotificationTemplateResponses];

export type DeleteNotificationTemplateBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/notification/v1.0/notification-templates/batch';
};

export type DeleteNotificationTemplateBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostNotificationTemplateBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/notification/v1.0/notification-templates/batch';
};

export type PostNotificationTemplateBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PutNotificationTemplateBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: '/o/notification/v1.0/notification-templates/batch';
};

export type PutNotificationTemplateBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetNotificationTemplateByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/notification/v1.0/notification-templates/by-external-reference-code/{externalReferenceCode}';
};

export type GetNotificationTemplateByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: NotificationTemplate;
};

export type GetNotificationTemplateByExternalReferenceCodeResponse = GetNotificationTemplateByExternalReferenceCodeResponses[keyof GetNotificationTemplateByExternalReferenceCodeResponses];

export type PutNotificationTemplateByExternalReferenceCodeData = {
    body?: NotificationTemplate;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: '/o/notification/v1.0/notification-templates/by-external-reference-code/{externalReferenceCode}';
};

export type PutNotificationTemplateByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: NotificationTemplate;
};

export type PutNotificationTemplateByExternalReferenceCodeResponse = PutNotificationTemplateByExternalReferenceCodeResponses[keyof PutNotificationTemplateByExternalReferenceCodeResponses];

export type GetNotificationTemplatesPageData = {
    body?: never;
    path?: never;
    query?: {
        aggregationTerms?: string;
        filter?: string;
        page?: string;
        pageSize?: string;
        search?: string;
        sort?: string;
        nestedFields?: string;
    };
    url: '/o/notification/v1.0/notification-templates';
};

export type GetNotificationTemplatesPageResponses = {
    /**
     * default response
     */
    default: PageNotificationTemplate;
};

export type GetNotificationTemplatesPageResponse = GetNotificationTemplatesPageResponses[keyof GetNotificationTemplatesPageResponses];

export type PostNotificationTemplateData = {
    body?: NotificationTemplate;
    path?: never;
    query?: never;
    url: '/o/notification/v1.0/notification-templates';
};

export type PostNotificationTemplateResponses = {
    /**
     * default response
     */
    default: NotificationTemplate;
};

export type PostNotificationTemplateResponse = PostNotificationTemplateResponses[keyof PostNotificationTemplateResponses];

export type PostNotificationTemplateCopyData = {
    body?: never;
    path: {
        notificationTemplateId: string;
    };
    query?: never;
    url: '/o/notification/v1.0/notification-templates/{notificationTemplateId}/copy';
};

export type PostNotificationTemplateCopyResponses = {
    /**
     * default response
     */
    default: NotificationTemplate;
};

export type PostNotificationTemplateCopyResponse = PostNotificationTemplateCopyResponses[keyof PostNotificationTemplateCopyResponses];

export type PostNotificationTemplatesPageExportBatchData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        search?: string;
        sort?: string;
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: '/o/notification/v1.0/notification-templates/export-batch';
};

export type PostNotificationTemplatesPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};