export type CreatorWritable = {
    additionalName?: string;
    familyName?: string;
    givenName?: string;
    id?: number;
    image?: string;
    name?: string;
    profileURL?: string;
};
// This file is auto-generated by @hey-api/openapi-ts

/**
 * Represents a collaborator for an entry.
 */
export type CollaboratorReadable = {
    /**
     * The collaborator actions for the shared asset.
     */
    actionIds: Array<string>;
    /**
     * Block of actions allowed by the user making the request.
     */
    readonly actions?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    creator?: CreatorReadable;
    /**
     * The expiration date to be a collaborator of the asset.
     */
    dateExpired?: string;
    /**
     * The collaborator external reference code.
     */
    readonly externalReferenceCode?: string;
    /**
     * The collaborator ID.
     */
    id?: number;
    /**
     * The collaborator name.
     */
    readonly name?: string;
    /**
     * The collaborator portrait.
     */
    readonly portrait?: string;
    /**
     * If the collaborator can share or not the asset.
     */
    share?: boolean;
    /**
     * The collaborator type.
     */
    type: string;
    readonly "x-class-name"?: string;
};

/**
 * Represents a collaborator for an entry.
 */
export type CollaboratorWritable = {
    /**
     * The collaborator actions for the shared asset.
     */
    actionIds: Array<string>;
    creator?: CreatorWritable;
    /**
     * The expiration date to be a collaborator of the asset.
     */
    dateExpired?: string;
    /**
     * The collaborator ID.
     */
    id?: number;
    /**
     * If the collaborator can share or not the asset.
     */
    share?: boolean;
    /**
     * The collaborator type.
     */
    type: string;
};

export type CreatorReadable = {
    /**
     * The author's additional name (e.g., middle name).
     */
    readonly additionalName?: string;
    /**
     * The type of the content.
     */
    readonly contentType?: string;
    /**
     * The external reference code of the author.
     */
    readonly externalReferenceCode?: string;
    /**
     * The author's surname.
     */
    readonly familyName?: string;
    /**
     * The author's first name.
     */
    readonly givenName?: string;
    /**
     * The author's ID.
     */
    readonly id?: number;
    /**
     * A relative URL to the author's profile image.
     */
    readonly image?: string;
    /**
     * The author's full name.
     */
    readonly name?: string;
    /**
     * A relative URL to the author's user profile. Optional field, can be embedded with nestedFields.
     */
    readonly profileURL?: string;
    /**
     * A list of userGroups information.
     */
    userGroupBriefs?: Array<UserGroupBrief>;
    readonly "x-class-name"?: string;
};

/**
 * A list of userGroups information.
 */
export type UserGroupBrief = {
    /**
     * The ID of the user group.
     */
    readonly id?: number;
    /**
     * The name of the user group.
     */
    readonly name?: string;
    readonly "x-class-name"?: string;
};

export type Facet = {
    facetCriteria?: string;
    facetValues?: Array<FacetValue>;
};

export type FacetValue = {
    numberOfOccurrences?: number;
    term?: string;
};

export type PageCollaboratorReadable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<CollaboratorReadable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type PageCollaboratorWritable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<CollaboratorWritable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

/**
 * Optional field with the audit events associated with this object entry, can be embedded with nestedFields
 */
export type AuditEventReadable = {
    readonly auditFieldChanges?: Array<AuditFieldChangeReadable>;
    creator?: CreatorReadable;
    readonly dateCreated?: string;
    readonly eventType?: string;
    readonly "x-class-name"?: string;
};

/**
 * Optional field with the audit events associated with this object entry, can be embedded with nestedFields
 */
export type AuditEventWritable = {
    creator?: CreatorWritable;
};

export type AuditFieldChangeReadable = {
    name?: string;
    newValue?: {
        [key: string]: unknown;
    };
    oldValue?: {
        [key: string]: unknown;
    };
    readonly "x-class-name"?: string;
};

export type AuditFieldChangeWritable = {
    name?: string;
    newValue?: {
        [key: string]: unknown;
    };
    oldValue?: {
        [key: string]: unknown;
    };
};

export type ParentTaxonomyCategoryReadable = {
    /**
     * The parent taxonomy category's external reference code.
     */
    externalReferenceCode?: string;
    readonly "x-class-name"?: string;
};

export type ParentTaxonomyCategoryWritable = {
    /**
     * The parent taxonomy category's external reference code.
     */
    externalReferenceCode?: string;
};

export type ParentTaxonomyVocabularyReadable = {
    /**
     * The parent category's `TaxonomyVocabulary` external reference code.
     */
    externalReferenceCode?: string;
    readonly "x-class-name"?: string;
};

export type ParentTaxonomyVocabularyWritable = {
    /**
     * The parent category's `TaxonomyVocabulary` external reference code.
     */
    externalReferenceCode?: string;
};

export type Permission = {
    actionIds?: Array<string>;
    roleExternalReferenceCode?: string;
    roleName?: string;
    roleType?: string;
};

export type ScopeReadable = {
    externalReferenceCode?: string;
    readonly "x-class-name"?: string;
    type?: "AssetLibrary" | "Site";
};

export type ScopeWritable = {
    externalReferenceCode?: string;
    type?: "AssetLibrary" | "Site";
};

export type StatusReadable = {
    code: number;
    label?: string;
    label_i18n?: string;
    readonly "x-class-name"?: string;
};

export type StatusWritable = {
    code: number;
    label?: string;
    label_i18n?: string;
};

/**
 * The categories associated with this object entry.
 */
export type TaxonomyCategoryBriefReadable = {
    /**
     * Optional field with the embedded taxonomy category, can be embedded with nestedFields
     */
    readonly embeddedTaxonomyCategory?: {
        [key: string]: unknown;
    };
    parentTaxonomyCategory?: ParentTaxonomyCategoryReadable;
    parentTaxonomyVocabulary?: ParentTaxonomyVocabularyReadable;
    scope?: ScopeReadable;
    /**
     * The category's external reference code.
     */
    taxonomyCategoryExternalReferenceCode?: string;
    /**
     * The category's ID. This can be used to retrieve more information in the `TaxonomyCategory` API.
     */
    readonly taxonomyCategoryId?: number;
    /**
     * The category's name.
     */
    readonly taxonomyCategoryName?: string;
    /**
     * The localized category's names.
     */
    readonly taxonomyCategoryName_i18n?: {
        [key: string]: string;
    };
    readonly "x-class-name"?: string;
};

/**
 * The categories associated with this object entry.
 */
export type TaxonomyCategoryBriefWritable = {
    parentTaxonomyCategory?: ParentTaxonomyCategoryWritable;
    parentTaxonomyVocabulary?: ParentTaxonomyVocabularyWritable;
    scope?: ScopeWritable;
    /**
     * The category's external reference code.
     */
    taxonomyCategoryExternalReferenceCode?: string;
};

export type Version = {
    readonly number?: number;
    readonly "x-class-name"?: string;
};

export type PagePermission = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<Permission>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type ValidationErrorReadable = {
    errorMessage?: string;
    objectFieldName?: string;
    objectValidationRuleExternalReferenceCode?: string;
    readonly "x-class-name"?: string;
};

export type ValidationErrorWritable = {
    errorMessage?: string;
    objectFieldName?: string;
    objectValidationRuleExternalReferenceCode?: string;
};

export type ValidationResponseReadable = {
    validationErrors?: Array<ValidationErrorReadable>;
    readonly "x-class-name"?: string;
};

export type ValidationResponseWritable = {
    validationErrors?: Array<ValidationErrorWritable>;
};

export type ValidationRequestReadable = {
    objectValidationRuleExternalReferenceCodes?: Array<string>;
    values?: NecessaryCookieEntryReadable;
    readonly "x-class-name"?: string;
};

export type ValidationRequestWritable = {
    objectValidationRuleExternalReferenceCodes?: Array<string>;
    values?: NecessaryCookieEntryWritable;
};

export type PageNecessaryCookieEntryReadable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<NecessaryCookieEntryReadable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
    readonly "x-schema-name"?: string;
};

export type PageNecessaryCookieEntryWritable = {
    lastPage?: number;
    totalCount?: number;
    items?: Array<NecessaryCookieEntryWritable>;
    actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    pageSize?: number;
    facets?: Array<Facet>;
    page?: number;
};

export type NecessaryCookieEntryReadable = {
    readonly actions?: {
        [key: string]: {
            [key: string]: string;
        };
    };
    /**
     * Optional field with the audit events associated with this object entry, can be embedded with nestedFields
     */
    readonly auditEvents?: Array<AuditEventReadable>;
    readonly creator?: string;
    readonly dateCreated?: string;
    readonly dateModified?: string;
    defaultLanguageId?: string;
    displayDate?: string;
    expirationDate?: string;
    externalReferenceCode?: string;
    /**
     * A relative URL to the page's rendered content.
     */
    friendlyUrlPath?: string;
    /**
     * The localized relative URLs to the page's rendered content.
     */
    friendlyUrlPath_i18n?: {
        [key: string]: string;
    };
    readonly id?: number;
    /**
     * A list of keywords describing the object entry.
     */
    keywords?: Array<string>;
    objectEntryFolderExternalReferenceCode?: string;
    objectEntryFolderId?: number;
    permissions?: Array<Permission>;
    reviewDate?: string;
    readonly scopeKey?: string;
    readonly status?: number;
    /**
     * The categories associated with this object entry.
     */
    taxonomyCategoryBriefs?: Array<TaxonomyCategoryBriefReadable>;
    readonly "x-class-name"?: string;
    readonly "x-schema-name"?: string;
    collectedData?: string;
    expiration?: string;
    host?: string;
    name: string;
    purpose?: string;
    type?: string;
};

export type NecessaryCookieEntryWritable = {
    defaultLanguageId?: string;
    displayDate?: string;
    expirationDate?: string;
    externalReferenceCode?: string;
    /**
     * A relative URL to the page's rendered content.
     */
    friendlyUrlPath?: string;
    /**
     * The localized relative URLs to the page's rendered content.
     */
    friendlyUrlPath_i18n?: {
        [key: string]: string;
    };
    /**
     * A list of keywords describing the object entry.
     */
    keywords?: Array<string>;
    objectEntryFolderExternalReferenceCode?: string;
    objectEntryFolderId?: number;
    permissions?: Array<Permission>;
    reviewDate?: string;
    /**
     * The categories associated with this object entry.
     */
    taxonomyCategoryBriefs?: Array<TaxonomyCategoryBriefWritable>;
    taxonomyCategoryIds?: Array<number>;
    collectedData?: string;
    expiration?: string;
    host?: string;
    name: string;
    purpose?: string;
    type?: string;
};

export type DeleteScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorData =
    {
        body?: never;
        path: {
            scopeKey: string;
            externalReferenceCode: string;
            type: string;
            collaboratorId: string;
        };
        query?: never;
        url: "/scopes/{scopeKey}/by-external-reference-code/{externalReferenceCode}/collaborators/by-type/{type}/{collaboratorId}";
    };

export type DeleteScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorResponses =
    {
        /**
         * default response
         */
        default: unknown;
    };

export type GetScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorData =
    {
        body?: never;
        path: {
            scopeKey: string;
            externalReferenceCode: string;
            type: string;
            collaboratorId: string;
        };
        query?: {
            fields?: string;
            nestedFields?: string;
            restrictFields?: string;
        };
        url: "/scopes/{scopeKey}/by-external-reference-code/{externalReferenceCode}/collaborators/by-type/{type}/{collaboratorId}";
    };

export type GetScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorResponses =
    {
        /**
         * default response
         */
        default: CollaboratorReadable;
    };

export type GetScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorResponse =
    GetScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorResponses[keyof GetScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorResponses];

export type PutScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorData =
    {
        body?: CollaboratorWritable;
        path: {
            scopeKey: string;
            externalReferenceCode: string;
            type: string;
            collaboratorId: string;
        };
        query?: never;
        url: "/scopes/{scopeKey}/by-external-reference-code/{externalReferenceCode}/collaborators/by-type/{type}/{collaboratorId}";
    };

export type PutScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorResponses =
    {
        /**
         * default response
         */
        default: CollaboratorReadable;
    };

export type PutScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorResponse =
    PutScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorResponses[keyof PutScopeScopeKeyByExternalReferenceCodeCollaboratorByTypeCollaboratorResponses];

export type GetScopeScopeKeyByExternalReferenceCodeCollaboratorsPageData = {
    body?: never;
    path: {
        scopeKey: string;
        externalReferenceCode: string;
    };
    query?: {
        fields?: string;
        nestedFields?: string;
        page?: string;
        pageSize?: string;
        restrictFields?: string;
    };
    url: "/scopes/{scopeKey}/by-external-reference-code/{externalReferenceCode}/collaborators";
};

export type GetScopeScopeKeyByExternalReferenceCodeCollaboratorsPageResponses =
    {
        /**
         * default response
         */
        default: PageCollaboratorReadable;
    };

export type GetScopeScopeKeyByExternalReferenceCodeCollaboratorsPageResponse =
    GetScopeScopeKeyByExternalReferenceCodeCollaboratorsPageResponses[keyof GetScopeScopeKeyByExternalReferenceCodeCollaboratorsPageResponses];

export type PostScopeScopeKeyByExternalReferenceCodeCollaboratorsPageData = {
    body?: Array<CollaboratorWritable>;
    path: {
        scopeKey: string;
        externalReferenceCode: string;
    };
    query?: never;
    url: "/scopes/{scopeKey}/by-external-reference-code/{externalReferenceCode}/collaborators";
};

export type PostScopeScopeKeyByExternalReferenceCodeCollaboratorsPageResponses =
    {
        /**
         * default response
         */
        default: PageCollaboratorReadable;
    };

export type PostScopeScopeKeyByExternalReferenceCodeCollaboratorsPageResponse =
    PostScopeScopeKeyByExternalReferenceCodeCollaboratorsPageResponses[keyof PostScopeScopeKeyByExternalReferenceCodeCollaboratorsPageResponses];

export type DeleteByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: "/by-external-reference-code/{externalReferenceCode}";
};

export type DeleteByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetByExternalReferenceCodeData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        fields?: string;
        nestedFields?: string;
        restrictFields?: string;
    };
    url: "/by-external-reference-code/{externalReferenceCode}";
};

export type GetByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type GetByExternalReferenceCodeResponse =
    GetByExternalReferenceCodeResponses[keyof GetByExternalReferenceCodeResponses];

export type PatchByExternalReferenceCodeData = {
    body?: NecessaryCookieEntryWritable;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: "/by-external-reference-code/{externalReferenceCode}";
};

export type PatchByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PatchByExternalReferenceCodeResponse =
    PatchByExternalReferenceCodeResponses[keyof PatchByExternalReferenceCodeResponses];

export type PutByExternalReferenceCodeData = {
    body?: NecessaryCookieEntryWritable;
    path: {
        externalReferenceCode: string;
    };
    query?: never;
    url: "/by-external-reference-code/{externalReferenceCode}";
};

export type PutByExternalReferenceCodeResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PutByExternalReferenceCodeResponse =
    PutByExternalReferenceCodeResponses[keyof PutByExternalReferenceCodeResponses];

export type DeleteByExternalReferenceCodeByVersionData = {
    body?: never;
    path: {
        externalReferenceCode: string;
        version: string;
    };
    query?: never;
    url: "/by-external-reference-code/{externalReferenceCode}/by-version/{version}";
};

export type DeleteByExternalReferenceCodeByVersionResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetByExternalReferenceCodeByVersionData = {
    body?: never;
    path: {
        externalReferenceCode: string;
        version: string;
    };
    query?: never;
    url: "/by-external-reference-code/{externalReferenceCode}/by-version/{version}";
};

export type GetByExternalReferenceCodeByVersionResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type GetByExternalReferenceCodeByVersionResponse =
    GetByExternalReferenceCodeByVersionResponses[keyof GetByExternalReferenceCodeByVersionResponses];

export type DeleteNecessaryCookieEntryBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: "/batch";
};

export type DeleteNecessaryCookieEntryBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostNecessaryCookieEntryBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: "/batch";
};

export type PostNecessaryCookieEntryBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PutNecessaryCookieEntryBatchData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        callbackURL?: string;
    };
    url: "/batch";
};

export type PutNecessaryCookieEntryBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetByExternalReferenceCodeVersionsPageData = {
    body?: never;
    path: {
        externalReferenceCode: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
    };
    url: "/by-external-reference-code/{externalReferenceCode}/versions";
};

export type GetByExternalReferenceCodeVersionsPageResponses = {
    /**
     * default response
     */
    default: PageNecessaryCookieEntryReadable;
};

export type GetByExternalReferenceCodeVersionsPageResponse =
    GetByExternalReferenceCodeVersionsPageResponses[keyof GetByExternalReferenceCodeVersionsPageResponses];

export type GetNecessaryCookieEntriesPageData = {
    body?: never;
    path?: never;
    query?: {
        aggregationTerms?: string;
        fields?: string;
        filter?: string;
        flatten?: string;
        nestedFields?: string;
        page?: string;
        pageSize?: string;
        restrictFields?: string;
        search?: string;
        sort?: string;
    };
    url: "/";
};

export type GetNecessaryCookieEntriesPageResponses = {
    /**
     * default response
     */
    default: PageNecessaryCookieEntryReadable;
};

export type GetNecessaryCookieEntriesPageResponse =
    GetNecessaryCookieEntriesPageResponses[keyof GetNecessaryCookieEntriesPageResponses];

export type PostNecessaryCookieEntryData = {
    body?: NecessaryCookieEntryWritable;
    path?: never;
    query?: never;
    url: "/";
};

export type PostNecessaryCookieEntryResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PostNecessaryCookieEntryResponse =
    PostNecessaryCookieEntryResponses[keyof PostNecessaryCookieEntryResponses];

export type PostByExternalReferenceCodeByVersionCopyData = {
    body?: never;
    path: {
        externalReferenceCode: string;
        version: string;
    };
    query?: never;
    url: "/by-external-reference-code/{externalReferenceCode}/by-version/{version}/copy";
};

export type PostByExternalReferenceCodeByVersionCopyResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PostByExternalReferenceCodeByVersionCopyResponse =
    PostByExternalReferenceCodeByVersionCopyResponses[keyof PostByExternalReferenceCodeByVersionCopyResponses];

export type PostByExternalReferenceCodeByVersionExpireData = {
    body?: never;
    path: {
        externalReferenceCode: string;
        version: string;
    };
    query?: never;
    url: "/by-external-reference-code/{externalReferenceCode}/by-version/{version}/expire";
};

export type PostByExternalReferenceCodeByVersionExpireResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PostByExternalReferenceCodeByVersionExpireResponse =
    PostByExternalReferenceCodeByVersionExpireResponses[keyof PostByExternalReferenceCodeByVersionExpireResponses];

export type PostNecessaryCookieEntriesPageExportBatchData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        search?: string;
        sort?: string;
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: "/export-batch";
};

export type PostNecessaryCookieEntriesPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type PostValidateData = {
    body?: ValidationRequestWritable;
    path?: never;
    query?: never;
    url: "/validate";
};

export type PostValidateResponses = {
    /**
     * default response
     */
    default: ValidationResponseReadable;
};

export type PostValidateResponse =
    PostValidateResponses[keyof PostValidateResponses];

export type PutByExternalReferenceCodeByVersionRestoreData = {
    body?: never;
    path: {
        externalReferenceCode: string;
        version: string;
    };
    query?: never;
    url: "/by-external-reference-code/{externalReferenceCode}/by-version/{version}/restore";
};

export type PutByExternalReferenceCodeByVersionRestoreResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PutByExternalReferenceCodeByVersionRestoreResponse =
    PutByExternalReferenceCodeByVersionRestoreResponses[keyof PutByExternalReferenceCodeByVersionRestoreResponses];

export type GetOpenApiData = {
    body?: never;
    path: {
        type: string;
    };
    query?: never;
    url: "/openapi.{type}";
};

export type GetOpenApiResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteNecessaryCookieEntryCollaboratorByTypeCollaboratorData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
        type: string;
        collaboratorId: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}/collaborators/by-type/{type}/{collaboratorId}";
};

export type DeleteNecessaryCookieEntryCollaboratorByTypeCollaboratorResponses =
    {
        /**
         * default response
         */
        default: unknown;
    };

export type GetNecessaryCookieEntryCollaboratorByTypeCollaboratorData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
        type: string;
        collaboratorId: string;
    };
    query?: {
        fields?: string;
        nestedFields?: string;
        restrictFields?: string;
    };
    url: "/{necessaryCookieEntryId}/collaborators/by-type/{type}/{collaboratorId}";
};

export type GetNecessaryCookieEntryCollaboratorByTypeCollaboratorResponses = {
    /**
     * default response
     */
    default: CollaboratorReadable;
};

export type GetNecessaryCookieEntryCollaboratorByTypeCollaboratorResponse =
    GetNecessaryCookieEntryCollaboratorByTypeCollaboratorResponses[keyof GetNecessaryCookieEntryCollaboratorByTypeCollaboratorResponses];

export type PutNecessaryCookieEntryCollaboratorByTypeCollaboratorData = {
    body?: CollaboratorWritable;
    path: {
        necessaryCookieEntryId: string;
        type: string;
        collaboratorId: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}/collaborators/by-type/{type}/{collaboratorId}";
};

export type PutNecessaryCookieEntryCollaboratorByTypeCollaboratorResponses = {
    /**
     * default response
     */
    default: CollaboratorReadable;
};

export type PutNecessaryCookieEntryCollaboratorByTypeCollaboratorResponse =
    PutNecessaryCookieEntryCollaboratorByTypeCollaboratorResponses[keyof PutNecessaryCookieEntryCollaboratorByTypeCollaboratorResponses];

export type GetNecessaryCookieEntryCollaboratorsPageData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
    };
    query?: {
        fields?: string;
        nestedFields?: string;
        page?: string;
        pageSize?: string;
        restrictFields?: string;
    };
    url: "/{necessaryCookieEntryId}/collaborators";
};

export type GetNecessaryCookieEntryCollaboratorsPageResponses = {
    /**
     * default response
     */
    default: PageCollaboratorReadable;
};

export type GetNecessaryCookieEntryCollaboratorsPageResponse =
    GetNecessaryCookieEntryCollaboratorsPageResponses[keyof GetNecessaryCookieEntryCollaboratorsPageResponses];

export type PostNecessaryCookieEntryCollaboratorsPageData = {
    body?: Array<CollaboratorWritable>;
    path: {
        necessaryCookieEntryId: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}/collaborators";
};

export type PostNecessaryCookieEntryCollaboratorsPageResponses = {
    /**
     * default response
     */
    default: PageCollaboratorReadable;
};

export type PostNecessaryCookieEntryCollaboratorsPageResponse =
    PostNecessaryCookieEntryCollaboratorsPageResponses[keyof PostNecessaryCookieEntryCollaboratorsPageResponses];

export type PostNecessaryCookieEntryCollaboratorsPageExportBatchData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
    };
    query?: {
        callbackURL?: string;
        contentType?: string;
        fieldNames?: string;
    };
    url: "/{necessaryCookieEntryId}/collaborators/export-batch";
};

export type PostNecessaryCookieEntryCollaboratorsPageExportBatchResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type DeleteNecessaryCookieEntryData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}";
};

export type DeleteNecessaryCookieEntryResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetNecessaryCookieEntryData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
    };
    query?: {
        fields?: string;
        nestedFields?: string;
        restrictFields?: string;
    };
    url: "/{necessaryCookieEntryId}";
};

export type GetNecessaryCookieEntryResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type GetNecessaryCookieEntryResponse =
    GetNecessaryCookieEntryResponses[keyof GetNecessaryCookieEntryResponses];

export type PatchNecessaryCookieEntryData = {
    body?: NecessaryCookieEntryWritable;
    path: {
        necessaryCookieEntryId: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}";
};

export type PatchNecessaryCookieEntryResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PatchNecessaryCookieEntryResponse =
    PatchNecessaryCookieEntryResponses[keyof PatchNecessaryCookieEntryResponses];

export type PutNecessaryCookieEntryData = {
    body?: NecessaryCookieEntryWritable;
    path: {
        necessaryCookieEntryId: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}";
};

export type PutNecessaryCookieEntryResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PutNecessaryCookieEntryResponse =
    PutNecessaryCookieEntryResponses[keyof PutNecessaryCookieEntryResponses];

export type DeleteNecessaryCookieEntryByVersionData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
        version: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}/by-version/{version}";
};

export type DeleteNecessaryCookieEntryByVersionResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetNecessaryCookieEntryByVersionData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
        version: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}/by-version/{version}";
};

export type GetNecessaryCookieEntryByVersionResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type GetNecessaryCookieEntryByVersionResponse =
    GetNecessaryCookieEntryByVersionResponses[keyof GetNecessaryCookieEntryByVersionResponses];

export type GetNecessaryCookieEntriesVersionsPageData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
    };
    query?: {
        page?: string;
        pageSize?: string;
    };
    url: "/{necessaryCookieEntryId}/versions";
};

export type GetNecessaryCookieEntriesVersionsPageResponses = {
    /**
     * default response
     */
    default: PageNecessaryCookieEntryReadable;
};

export type GetNecessaryCookieEntriesVersionsPageResponse =
    GetNecessaryCookieEntriesVersionsPageResponses[keyof GetNecessaryCookieEntriesVersionsPageResponses];

export type GetNecessaryCookieEntryPermissionsPageData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
    };
    query?: {
        fields?: string;
        nestedFields?: string;
        restrictFields?: string;
        roleNames?: string;
    };
    url: "/{necessaryCookieEntryId}/permissions";
};

export type GetNecessaryCookieEntryPermissionsPageResponses = {
    /**
     * default response
     */
    default: PagePermission;
};

export type GetNecessaryCookieEntryPermissionsPageResponse =
    GetNecessaryCookieEntryPermissionsPageResponses[keyof GetNecessaryCookieEntryPermissionsPageResponses];

export type PutNecessaryCookieEntryPermissionsPageData = {
    body?: Array<Permission>;
    path: {
        necessaryCookieEntryId: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}/permissions";
};

export type PutNecessaryCookieEntryPermissionsPageResponses = {
    /**
     * default response
     */
    default: PagePermission;
};

export type PutNecessaryCookieEntryPermissionsPageResponse =
    PutNecessaryCookieEntryPermissionsPageResponses[keyof PutNecessaryCookieEntryPermissionsPageResponses];

export type PostNecessaryCookieEntryByVersionCopyData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
        version: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}/by-version/{version}/copy";
};

export type PostNecessaryCookieEntryByVersionCopyResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PostNecessaryCookieEntryByVersionCopyResponse =
    PostNecessaryCookieEntryByVersionCopyResponses[keyof PostNecessaryCookieEntryByVersionCopyResponses];

export type PostNecessaryCookieEntryByVersionExpireData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
        version: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}/by-version/{version}/expire";
};

export type PostNecessaryCookieEntryByVersionExpireResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PostNecessaryCookieEntryByVersionExpireResponse =
    PostNecessaryCookieEntryByVersionExpireResponses[keyof PostNecessaryCookieEntryByVersionExpireResponses];

export type PutNecessaryCookieEntryByVersionRestoreData = {
    body?: never;
    path: {
        necessaryCookieEntryId: string;
        version: string;
    };
    query?: never;
    url: "/{necessaryCookieEntryId}/by-version/{version}/restore";
};

export type PutNecessaryCookieEntryByVersionRestoreResponses = {
    /**
     * default response
     */
    default: NecessaryCookieEntryReadable;
};

export type PutNecessaryCookieEntryByVersionRestoreResponse =
    PutNecessaryCookieEntryByVersionRestoreResponses[keyof PutNecessaryCookieEntryByVersionRestoreResponses];

export type ClientOptions = {
    baseUrl:
        | "http://localhost:8080/o/necessary-cookies-entries/"
        | (string & {});
};
